### ISSUE TITLE
Module dependencies in Expert Mode

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#103]
**Is your feature request related to a problem? Please describe.**

I tested all modules one by one and found some dependencies.
S13 requires S12 and S14 requires S12 and S13:

![kép](https://user-images.githubusercontent.com/98665813/227719659-38734871-e9b4-4032-bd61-dde803031e77.png)

![kép](https://user-images.githubusercontent.com/98665813/227719671-fef0531b-9aa2-4e44-8ef4-9086293461ad.png)

S20 needs S115:

![kép](https://user-images.githubusercontent.com/98665813/227719684-60d2efc1-953b-4a76-aa56-9aed4b255719.png)

S25 uses S24:

![kép](https://user-images.githubusercontent.com/98665813/227719702-5b7b385b-81af-4f0e-9bba-93081fbe76f0.png)

S109 requires S108:

![kép](https://user-images.githubusercontent.com/98665813/227719725-7dec581e-7c3b-43fd-a47d-39629e17465b.png)

S116 wanted to use S115:

![kép](https://user-images.githubusercontent.com/98665813/227719747-6a7b1bd5-1d1d-48df-98ab-43a6f7262fe5.png)

Each modul can be selected one by one and if the user does not have the knowledge of exactly which module does what, they cannot effectively select for the test.

**Describe the solution you'd like**

It would be nice to have a way to display the dependencies in the list if someone is using the expert mode:
![kép](https://user-images.githubusercontent.com/98665813/227719991-00e146d3-8847-46ea-b3a1-d2151fa34787.png)

**Describe alternatives you've considered**

I think the framed solution would show the related modules well, but if someone selects one that has a dependency it could also be selected automatically.

**Additional context**

- If you choose expert mode, no module is selected by default. I think that in practise we often need almost all modules and want to leave some out, so the list of modules should be all selected except for S120_cwe_checker, and then we should just manually select the one or ones we don't want to use in the actual test execution. Functions such as select all, deselect all and reverse selection could also help the user to manage the list.

- If the module_blacklist.txt file exists then EMBArk could take into account the disabled modules and in this case gray out them on the page so that they cannot be selected. At the moment even though they are disabled in the text file, they still run when manually selected.

![kép](https://user-images.githubusercontent.com/98665813/227720838-2429f949-e7bb-4f76-8795-3a812efaa253.png)

![kép](https://user-images.githubusercontent.com/98665813/227720858-de4bb23f-0d66-4fc8-b38c-71abb6848a70.png)

![kép](https://user-images.githubusercontent.com/98665813/227720869-b9764346-8483-465a-959f-c6bfe3e08781.png)

- I think the following modules are missing from the page but the scripts are in modules folder:

S17_apk_check.sh
S26_kernel_vuln_verifier.sh
S36_lighttpd.sh

**Comment by m-1-k-3** [comment]
As it is called "Expert mode" the expert should know what todo. We put this on our future todo list.
Pull requests are welcome.

**Comment by BenediktMKuehne** [comment]
Putting this into a wiki page for now.
[expert-mode](https://github.com/e-m-b-a/embark/wiki/expert-mode)
