### ISSUE TITLE
Pip-enviroment not found!

### ISSUE THREAD

**Issue by Hiran2912** [e-m-b-a/embark#106]
**Describe the bug**

**To Reproduce**
1. EMBArk installation (default mode/docker-mode)
2. Start EMBArk: sudo ./run-server.sh

 - OS: [Kali Linux 2023.1]

**Comment by m-1-k-3** [comment]
Please check the prerequisites here: https://github.com/e-m-b-a/embark/wiki/Installation#prerequisites

EMBArk is only tested on Ubuntu 22.04. Please try it on a supported environment.
