### ISSUE TITLE
Pipfile.lock install faild

### ISSUE THREAD

**Issue by anyu2009** [e-m-b-a/embark#107]
Installation of the firmware scanning environment EMBArk
Reading package lists...
Building dependency tree...
Reading state information...
build-essential is already the newest version (12.9).
default-libmysqlclient-dev is already the newest version (1.1.0).
The following packages were automatically installed and are no longer required:
  g++-9 libstdc++-9-dev
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 461 not upgraded.
Requirement already satisfied: pipenv in /usr/lib/python3/dist-packages (2022.12.19)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
www-embark

Install embark daemon

Creating SSL Cert

Certs already generated, skipping

Install hostnames for local dns-resolve

hostname already in use!
Installing dependencies from Pipfile.lock (bcd04c)...
An error occurred while installing apscheduler==3.10.0 ; python_version >= '3.6' --hash=sha256:575299f20073c60a2cc9d4fa5906024cdde33c5c0ce6087c4e3c14be3b50fdd4 --hash=sha256:a49fc23269218416f0e41890eea7a75ed6b284f10630dcfe866ab659621a3696! Will try again.
An error occurred while installing asgiref==3.6.0 ; python_version >= '3.7' --hash=sha256:9567dfe7bd8d3c8c892227827c41cce860b368104c3431da67a0c5a65a949506 --hash=sha256:71e68008da809b957b7ee4b43dbccff33d1b23519fb8344e33f049897077afac! Will try again.
An error occurred while installing async-timeout==4.0.2 ; python_version >= '3.6' --hash=sha256:8ca1e4fcf50d07413d66d1a5e416e42cfdf5851c981d679a09851a6853383b3c --hash=sha256:2163e1640ddb52b7a8c80d0a67a08587e5d245cc9c553a74a847056bc2976b15! Will try again.
An error occurred while installing attrs==22.2.0 ; python_version >= '3.6' --hash=sha256:29e95c7f6778868dbd49170f98f8818f78f3dc5e0e37c0b1f474e3561b240836 --hash=sha256:c9227bfc2f01993c03f68db37d1d15c9690188323c067c641f1a35ca58185f99! Will try again.
An error occurred while installing autobahn==23.1.2 ; python_version >= '3.7' --hash=sha256:c5ef8ca7422015a1af774a883b8aef73d4954c9fcd182c9b5244e08e973f7c3a! Will try again.
An error occurred while installing automat==22.10.0 --hash=sha256:e56beb84edad19dcc11d30e8d9b895f75deeb5ef5e96b84a467066b3b84bb04e --hash=sha256:c3164f8742b9dc440f3682482d32aaff7bb53f71740dd018533f9de286b64180! Will try again.
An error occurred while installing certifi==2022.12.7 ; python_version >= '3.6' --hash=sha256:35824b4c3a97115964b408844d64aa14db1cc518f6562e8d7261699d1350a9e3 --hash=sha256:4ad3232f5e926d6718ec31cfc1fcadfde020920e278684144551c91769c7bc18! Will try again.
An error occurred while installing cffi==1.15.1 --hash=sha256:04ed324bda3cda42b9b695d51bb7d54b680b9719cfab04227cdd1e04e5de3104 --hash=sha256:198caafb44239b60e252492445da556afafc7d1e3ab7a1fb3f0584ef6d742375 --hash=sha256:2012c72d854c2d03e45d06ae57f40d78e5770d252f195b93f581acf3ba44496e --hash=sha256:3799aecf2e17cf585d977b780ce79ff0dc9b78d799fc694221ce814c2c19db83 --hash=sha256:1e74c6b51a9ed6589199c787bf5f9875612ca4a8a0785fb2d4a84429badaf22a --hash=sha256:3bcde07039e586f91b45c88f8583ea7cf7a0770df3a1649627bf598332cb6984 --hash=sha256:40f4774f5a9d4f5e344f31a32b5096977b5d48560c5592e2f3d2c4374bd543ee --hash=sha256:3d08afd128ddaa624a48cf2b859afef385b720bb4b43df214f85616922e6a5ac --hash=sha256:a66d3508133af6e8548451b25058d5812812ec3798c886bf38ed24a98216fab2 --hash=sha256:87c450779d0914f2861b8526e035c5e6da0a3199d8f1add1a665e1cbc6fc6d02 --hash=sha256:a0f100c8912c114ff53e1202d0078b425bee3649ae34d7b070e9697f93c5d52d --hash=sha256:e263d77ee3dd201c3a142934a086a4450861778baaeeb45db4591ef65550b0a6 --hash=sha256:3548db281cd7d2561c9ad9984681c95f7b0e38881201e157833a2342c30d5e8c --hash=sha256:8102eaf27e1e448db915d08afa8b41d6c7ca7a04b7d73af6514df10a3e74bd82 --hash=sha256:a591fe9e525846e4d154205572a029f653ada1a78b93697f3b5a8f1f2bc055b9 --hash=sha256:e00b098126fd45523dd056d2efba6c

**Comment by BenediktMKuehne** [comment]
Sorry, I can't really help you like that.
The `pipenv install ` command is throwing errors, I can tell only this much

Try executing that command by hand.
Since this is the python-package-manager it can have a number of reasons.
* no internet connection
* pip needs a proxy setup
* etc

**Comment by m-1-k-3** [comment]
@Roksolana969 can we have an update on this issue?

**Comment by m-1-k-3** [comment]
Please re-open it with further details.
