### ISSUE TITLE
Getting started with Embark

### ISSUE THREAD

**Issue by aspi-dwtt** [e-m-b-a/embark#11]
I want to try this tool, but i got stuck on getting it up and running.

- I Created a hyper-VM, and installed linux kali on it.
- I cloned the embark repository
- And I started the installer from whitin the embark directory: 
    sudo ./installer.sh -F
- The next step should be registering a new user, but there's nothing listening on port 80
What am I missing here?

**Comment by p4cx** [comment]
We are happy that you want to use it. Can you please share the output of the installation process? 
Additional the output of `docker-compose ps` would be helpful. 

Maybe there is a bit of a hiccup and you have to restart all docker-compose containers: `docker-compose restart`.

**Comment by aspi-dwtt** [comment]
I'm sorry I don't have the output of the installation process anymore.

In the meantime I installed emba, and I have the first firmware check running!

I will retry embark at a later stage.

Thank you

**Comment by p4cx** [comment]
Have fun testing with EMBA - we hope you will find many interesting stuff ;) 

Please don't hesitate to open a new issue, if something is wrong or a pull request, if you want to add new features. 
I will close this one now. Have a nice day.
