### ISSUE TITLE
EMBArk not working due to emba not installing correctly(using latest commit)

### ISSUE THREAD

**Issue by hutchYy** [e-m-b-a/embark#110]
Hey 👋

**Describe the bug**
I'm currently testing out EMBArk and I had couple issue setting it up.
It seems that currently freetz-ng and fitmg fail to install.

This might be related to the fact that the current emba is not an official release but instead the latest master development branch([107d304](https://github.com/e-m-b-a/emba/tree/107d304a59217a27b086b821c9a63822a09b93ec)).

**To Reproduce**
1. Clone the current EMBArk repository
1. EMBArk installation (default mode)
3. Fails

**Expected behavior**
Just EMBArk that finish the installation without failing

**Desktop (please complete the following information):**
I'm currently using an Ubuntu 22.04 LTS server as recommended.

**Screenshots**
Here is a screenshot of the issue:
![image](https://user-images.githubusercontent.com/39437167/230501728-bfded855-b1d1-432b-80ed-f6bee2bab574.png)

**Comment by m-1-k-3** [comment]
We started to get rid of some not needed extractor modules in EMBA. The used docker image is already updated but not the EMBA version of EMBArk. Till EMBArk is updated you can update your EMBA installation manually in the EMBA subdirectory.

Another workaround is to change the dependency helper module in emba/helpers/helpers_emba_dependency_check.sh 

https://github.com/e-m-b-a/emba/blob/2f85d3049a4cde9122d4e4d45b89da9599e917d6/helpers/helpers_emba_dependency_check.sh#L459

https://github.com/e-m-b-a/emba/blob/2f85d3049a4cde9122d4e4d45b89da9599e917d6/helpers/helpers_emba_dependency_check.sh#L462

**Comment by BenediktMKuehne** [comment]
`git submodule update --remote` should remedy that. It's just untested for now
