### ISSUE TITLE
main-dashboard empty and bugged

### ISSUE THREAD

**Issue by BenediktMKuehne** [e-m-b-a/embark#121]
**Describe the bug**
script has major flaws and problems.

**To Reproduce**
1. EMBArk installation (default mode/docker-mode)
2. Start EMBArk: sudo ./run-server.sh
3. run any fw
4. main dash empty
5. See error

**Expected behavior**
main dashboard is expected to display clear and concise information

**Screenshots**
![image](https://user-images.githubusercontent.com/62940240/236241052-e1b8602b-aa8b-405d-8814-b3ddb9539c70.png)

**Desktop (please complete the following information):**
 - OS: Ubu22.04

**Additional context**
😠

**Comment by m-1-k-3** [comment]
@BenediktMKuehne this should be fixed. Can we close this issue?

**Comment by torabi12** [comment]
> @BenediktMKuehne this should be fixed. Can we close this issue?

I am going to do some tests this morning, but it will be fine for sure. Will share the results afternoon...

**Comment by torabi12** [comment]
I executed 3 scans, all of them were working:

![image](https://github.com/e-m-b-a/embark/assets/98665813/109a91b9-4151-4e93-b2a8-7f00b4993a2f)
