### ISSUE TITLE
emba_runs does not exist

### ISSUE THREAD

**Issue by zhjygit** [e-m-b-a/embark#130]
Docker Interface - Device "emba_runs" does not exist.
    Missing Docker-Interface - check your installation
    Trying to auto-maintain the docker interface ...
Device "emba_runs" does not exist.
    Use  $systemctl restart NetworkManager docker or reset the docker interface manually ($ docker network rm emba_runs)
    cve-search - testing

使用ifconfig查询，网卡是docker0.执行installer.sh -d的时候会自动查找emba_runs，找不到的情况下就报上面的错误。这个问题怎么解决。

**Comment by m-1-k-3** [comment]
Please include all the needed infos from the template. Closing for now. Please reopen it with the needed information.
