### ISSUE TITLE
Question regarding disk space, startup shell, and server configuration

### ISSUE THREAD

**Issue by qingyuanyou** [e-m-b-a/embark#141]
Hi Teams,

please help me with the below questions,
1. How much disk space is required for the analysis?
I currently have only 9GB of available disk space, and when I tried to run the analysis, it warned me and stopped due to the lack of space. There were also some useless temporary containers left.
![image](https://github.com/e-m-b-a/embark/assets/20557108/3c8082de-a6f6-4baa-b7fc-a515824cb9e8)
![1690555702(1)](https://github.com/e-m-b-a/embark/assets/20557108/ae57c841-43ee-4402-ab04-a06a842e8ea5)
===
2.Is there a more convenient startup shell due to the project  started successfully last time?
===
3. If I plan to use the project frequently, could you recommend a server configuration? Currently, I am considering using Ubuntu 22.04 with 4 CPUs, 16GB of RAM, and 50GB of disk space

Thank you for your hard work and support.
Best regards

**Comment by m-1-k-3** [comment]
Hi @qingyuanyou 

The "running out of disk space protection" was never finished and is currently not fully working. I will remove it for now from EMBA and come back to this topic later.

**Comment by m-1-k-3** [comment]
regarding minimum disk space - this depends on how many firmware images and which firmware images you are testing. Probably the prerequisites section can help you https://github.com/e-m-b-a/emba/wiki/Installation#prerequisites

**Comment by qingyuanyou** [comment]
Got it, thanks for your support!

**Comment by secsonthebeach** [comment]
Hello, can I dovetail off of this issue?
I have been asked to configure our server with a separate storage drive for the firmware images and log files.
It looks like the FW images are uploaded to `/var/www/media` and the logs are output to `/var/www/emba_logs`

Is there already a configuration that I’ve overlooked to specify these locations?
If I were to just mount these location to another disk, would that be sufficient?

Also, re: start-up… is the use of `run-server.sh` intended to be manual each time? I would like the server to start on boot. Should I create my own service for this, or is there one provided that I’ve overlooked?

**Comment by secsonthebeach** [comment]
> Hello, can I dovetail off of this issue? I have been asked to configure our server with a separate storage drive for the firmware images and log files. It looks like the FW images are uploaded to `/var/www/media` and the logs are output to `/var/www/emba_logs`
> 
> Is there already a configuration that I’ve overlooked to specify these locations? If I were to just mount these location to another disk, would that be sufficient?
> 
> Also, re: start-up… is the use of `run-server.sh` intended to be manual each time? I would like the server to start on boot. Should I create my own service for this, or is there one provided that I’ve overlooked?

Creating a service to execute `run-server.sh` with my relevant alias option seems to be working well.

I was also able to create symbolic links for the media and emba_logs directories, so that they can be maintained on a separate storage drive. It all seems to work as expected!
