### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#145]
**Describe the bug**
I used a new Ubuntu Server 22.04.3 VM for EMBArk installation, but at the beginning (Dependency check section) it gave the prompt back with these errors:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/b5447d76-a23d-4501-90ef-f59ed33c9531)

**To Reproduce**
1. EMBArk installation (default mode)
2. See error

**Expected behavior**
Installation should go on.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 22.04.3

**Comment by BenediktMKuehne** [comment]
Will check that as soon as I'm able too

**Comment by BenediktMKuehne** [comment]
The problem here is the wrong EMBA version

Do a:
`git submodule init`
followed by
`git submodule update --remote`

before installing

**Comment by 0rShemesh** [comment]
> The problem here is the wrong EMBA version
> 
> Do a: `git submodule init` followed by `git submodule update --remote`
> 
> before installing

Doesn't work. still same problem.

**Comment by BenediktMKuehne** [comment]
Could you provide me with the installation log.
Either the terminal output OR `emba/install.log`

**Comment by torabi12** [comment]
I did also the same but got the above errors again.

![kép](https://github.com/e-m-b-a/embark/assets/98665813/e077fb5e-00bc-4622-ad44-def589444ecc)

`$ sudo ./installer.sh -d`

![kép](https://github.com/e-m-b-a/embark/assets/98665813/d7df6827-c00f-4c38-9b19-daa98cb27d82)

![kép](https://github.com/e-m-b-a/embark/assets/98665813/1748760e-c56b-48fc-bb08-6b75e0d8d008)

and the log file from the system:
[install.log](https://github.com/e-m-b-a/embark/files/12453111/install.log)

**Comment by 0rShemesh** [comment]
> I did also the same but got the above errors again.
> 
> ![kép](https://user-images.githubusercontent.com/98665813/263665640-e077fb5e-00bc-4622-ad44-def589444ecc.png)
> 
> `$ sudo ./installer.sh -d`
> 
> ![kép](https://user-images.githubusercontent.com/98665813/263665986-d7df6827-c00f-4c38-9b19-daa98cb27d82.png)
> 
> ![kép](https://user-images.githubusercontent.com/98665813/263666018-1748760e-c56b-48fc-bb08-6b75e0d8d008.png)
> 
> and the log file from the system: [install.log](https://github.com/e-m-b-a/embark/files/12453111/install.log)

Turns out that the command `file` not built-in command on `Ubuntu Server 22.04.3 LTS`
and you should install that before installing EMBA.ark (file command requires by EMBA)
By:
```bash
sudo apt-get install -y file
``` 
But installing  `file` solve part of the problem.

@BenediktMKuehne I've the same error as @torabi12
when I'm trying to reinstall in the second attempt.

After reinstall EMBArk the apt become corrupted (no matter how many I've changed the sources.list it still not work)

**Comment by BenediktMKuehne** [comment]
> I did also the same but got the above errors again.
> 
> ![kép](https://user-images.githubusercontent.com/98665813/263665640-e077fb5e-00bc-4622-ad44-def589444ecc.png)
> 
> `$ sudo ./installer.sh -d`
> 
> ![kép](https://user-images.githubusercontent.com/98665813/263665986-d7df6827-c00f-4c38-9b19-daa98cb27d82.png)
> 
> ![kép](https://user-images.githubusercontent.com/98665813/263666018-1748760e-c56b-48fc-bb08-6b75e0d8d008.png)
> 
> and the log file from the system: [install.log](https://github.com/e-m-b-a/embark/files/12453111/install.log)

That's an issue with your apt package manager and not directly related to EMBA or EMBArk.

All I can do is recommend switching to the main ubuntu update servers.
As long as `sudo apt update` doesn't work the installation will not work correctly.

**Comment by BenediktMKuehne** [comment]
This might help:
![image](https://github.com/e-m-b-a/embark/assets/62940240/9c33c5de-fe9c-4892-b99b-d544bea6e21b)
![image](https://github.com/e-m-b-a/embark/assets/62940240/5ac00245-1282-4406-ae23-8c86f514e7bb)

**Comment by 0rShemesh** [comment]
> > I did also the same but got the above errors again.
> > ![kép](https://user-images.githubusercontent.com/98665813/263665640-e077fb5e-00bc-4622-ad44-def589444ecc.png)
> > `$ sudo ./installer.sh -d`
> > ![kép](https://user-images.githubusercontent.com/98665813/263665986-d7df6827-c00f-4c38-9b19-daa98cb27d82.png)
> > ![kép](https://user-images.githubusercontent.com/98665813/263666018-1748760e-c56b-48fc-bb08-6b75e0d8d008.png)
> > and the log file from the system: [install.log](https://github.com/e-m-b-a/embark/files/12453111/install.log)
> 
> That's an issue with your apt package manager and not directly related to EMBA or EMBArk.
> 
> All I can do is recommend switching to the main ubuntu update servers. As long as `sudo apt update` doesn't work the installation will not work correctly.

That's incorrect it related to EMBA .
After EMBA failed to install this error accured .

Edit:
I guess the error accured because one of the Installers:
https://github.com/e-m-b-a/emba/tree/master/installer

**Comment by BenediktMKuehne** [comment]
@0rShemesh please open a separate (new) issue for the `file` dependency

The issues might be related, but don't appear to be the same.

**Comment by torabi12** [comment]
> > I did also the same but got the above errors again.
> > ![kép](https://user-images.githubusercontent.com/98665813/263665640-e077fb5e-00bc-4622-ad44-def589444ecc.png)
> > `$ sudo ./installer.sh -d`
> > ![kép](https://user-images.githubusercontent.com/98665813/263665986-d7df6827-c00f-4c38-9b19-daa98cb27d82.png)
> > ![kép](https://user-images.githubusercontent.com/98665813/263666018-1748760e-c56b-48fc-bb08-6b75e0d8d008.png)
> > and the log file from the system: [install.log](https://github.com/e-m-b-a/embark/files/12453111/install.log)
> 
> Turns out that the command `file` not built-in command on `Ubuntu Server 22.04.3 LTS` and you should install that before installing EMBA.ark (file command requires by EMBA) By:
> 
> ```shell
> sudo apt-get install -y file
> ```
> 
> But installing `file` solve part of the problem.
> 
> @BenediktMKuehne I've the same error as @torabi12 when I'm trying to reinstall in the second attempt.
> 
> After reinstall EMBArk the apt become corrupted (no matter how many I've changed the sources.list it still not work)

It seems to me that `file` is available by default on Ubuntu Server 22.04.3:
![kép](https://github.com/e-m-b-a/embark/assets/98665813/c4a9ec8d-ddf5-4683-a0ef-6e13cff22ccd)

**Comment by torabi12** [comment]
> > I did also the same but got the above errors again.
> > ![kép](https://user-images.githubusercontent.com/98665813/263665640-e077fb5e-00bc-4622-ad44-def589444ecc.png)
> > `$ sudo ./installer.sh -d`
> > ![kép](https://user-images.githubusercontent.com/98665813/263665986-d7df6827-c00f-4c38-9b19-daa98cb27d82.png)
> > ![kép](https://user-images.githubusercontent.com/98665813/263666018-1748760e-c56b-48fc-bb08-6b75e0d8d008.png)
> > and the log file from the system: [install.log](https://github.com/e-m-b-a/embark/files/12453111/install.log)
> 
> That's an issue with your apt package manager and not directly related to EMBA or EMBArk.
> 
> All I can do is recommend switching to the main ubuntu update servers. As long as `sudo apt update` doesn't work the installation will not work correctly.

I think the `apt` works fine on my side:
![kép](https://github.com/e-m-b-a/embark/assets/98665813/f6299248-42cf-4e12-9f3a-98cfc113d06d)

**Comment by torabi12** [comment]
> This might help: ![image](https://user-images.githubusercontent.com/62940240/263673790-9c33c5de-fe9c-4892-b99b-d544bea6e21b.png) ![image](https://user-images.githubusercontent.com/62940240/263673918-5ac00245-1282-4406-ae23-8c86f514e7bb.png)

I tried the us.archive.ubuntu.com and the main server also but did not work, I got the same errors like before and the EMBArk installation terminated.
This is the log from emba:
[install.log](https://github.com/e-m-b-a/embark/files/12462212/install.log)

Before EMBArk installation the `apt update / apt upgrade` commands work fine for HU, US and Main mirrors, but in the EMBA installer don't on my side.

**Comment by 0rShemesh** [comment]
After check EMBAark the Automated install doesn't work on Kali-Linux latest clean image

**Comment by torabi12** [comment]
> After check EMBAark the Automated install doesn't work on Kali-Linux latest clean image

EMBArk needs Ubuntu Server OS, see the wiki:
https://github.com/e-m-b-a/embark/wiki/Installation#prerequisites

**Comment by 0rShemesh** [comment]
> > After check EMBAark the Automated install doesn't work on Kali-Linux latest clean image
> 
> EMBArk needs Ubuntu Server OS, see the wiki: https://github.com/e-m-b-a/embark/wiki/Installation#prerequisites

Yah but the Automated installation broken on ubuntu.
I'm just trying to boot it up.

**Comment by torabi12** [comment]
> 

I think this will solve the problem soon:
https://github.com/e-m-b-a/emba/issues/765

**Comment by torabi12** [comment]
EMBArk installation on Ubuntu Server is working again:)
[install.log](https://github.com/e-m-b-a/embark/files/12506059/install.log)

Thank you the fix!

**Comment by 0rShemesh** [comment]
Currently I've bug with the cve-search 
It always fails to find it
