### ISSUE TITLE
WebSocket connection to 'ws://[my_ip]:8001/ws/progress/' failed

### ISSUE THREAD

**Issue by qingyuanyou** [e-m-b-a/embark#146]
**Describe the bug**
after I updated a file to analyze, console error  WebSocket connection to 'ws://[my_ip]:8001/ws/progress/' failed, the service shutdown. 

**To Reproduce**
1. select a file to analyze
2. error in WebSocket connection to 'ws://[my_ip]:8001/ws/progress/' failed: 
(anonymous) @ serviceDashboard.js:103
3. the service shutted down but analyze docker is still running.

**Expected behavior**
I want the system not to be accidentally stopped after normal operation, I would appreciate if you could help me

**Screenshots**
![image](https://github.com/e-m-b-a/embark/assets/20557108/e5e7e0b7-44a5-4534-80d1-1c1179ae022a)
![image](https://github.com/e-m-b-a/embark/assets/20557108/d907c9c6-d34e-4cd9-8964-de2eb8dfc514)
![image](https://github.com/e-m-b-a/embark/assets/20557108/cde9e897-2215-4ba3-998d-5f0d7ae7f6cd)
![image](https://github.com/e-m-b-a/embark/assets/20557108/24c9bce5-989b-470d-b078-473f8eab1420)

**Desktop (please complete the following information):**
![image](https://github.com/e-m-b-a/embark/assets/20557108/4451298e-67df-4a22-9099-f1a780e8f008)
![image](https://github.com/e-m-b-a/embark/assets/20557108/27673f17-b9ae-4bd5-85d7-dbbc61ba48f6)
![image](https://github.com/e-m-b-a/embark/assets/20557108/6189819e-7f59-43b7-9768-78b0fbe3cb7d)

Thanks,

**Comment by BenediktMKuehne** [comment]
I'm tracking that currently.
We have a problem within our logreader, which causes the whole WSGI to crash.
Will keep you updated with a fix

**Comment by BenediktMKuehne** [comment]
Current master has a work-around for this issue.
It's not a fix, but at this moment, the only way to make the wsgi work.

**Comment by qingyuanyou** [comment]
Hi Team,

Thanks for update. 
I will try right now. 

:)

**Comment by qingyuanyou** [comment]
update on my side.
the good news is it works! thanks.
however it is too slow to load pages. TAT

**Comment by BenediktMKuehne** [comment]
closed with #154
