### ISSUE TITLE
Missing dependency - file

### ISSUE THREAD

**Issue by 0rShemesh** [e-m-b-a/embark#148]
**Missing dependency**
Missing the package `file`.
That cause to the function [import_helper](https://github.com/e-m-b-a/embark/blob/49c8c43ba233f773b82f9bd26b92ef63823d1a4f/installer.sh#L54) to fail 

**To Reproduce**
1. Create VM of Ubuntu Server 22.04.3 LTS with 50GB and 16GB Ram
2.run the following commands:
```
 git clone --recursive -j 8 https://github.com/e-m-b-a/embark.git
cd embark
sudo git submodule update --remote --merge
cd emba
git checkout master && git pull
cd ..
sudo ./installer.sh -d
```

**Expected behavior**
Install everything 

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu Server 22.04.03 Lts]

**Additional context**
Also the installation still doesn't work in clean installation on clean VM.

**Comment by m-1-k-3** [comment]
This issue should be already resolved from EMBA side. If not, please re-open it
