### ISSUE TITLE
File Format and Link Concatenation Issues in Embark Redirection Links

### ISSUE THREAD

**Issue by qingyuanyou** [e-m-b-a/embark#153]
Hi Team,

please help with the below issues,

1. According to Embark's log output, there seems to be a non-existent directory or file, even though it actually exists. Fortunately, this issue does not seem to have any impact on the program's functionality.
![image](https://github.com/e-m-b-a/embark/assets/20557108/5f70163f-66d0-448b-966f-fc0b4105fd52)
2. there are two issues when I open the redirection link in emba log. 
The first one is a file format problem,
![cf26d5f3d2323832b738d614fad78e9](https://github.com/e-m-b-a/embark/assets/20557108/e00af393-1130-4e07-9d45-cec675b47dbc)
the second one is a link concatenation error that prevents the file from being found. There are error links present in both the EMBA logs and the embark system. I fixed some error link, however it happens frequently.
![3837b48cd22dfb48a215223d68920a6](https://github.com/e-m-b-a/embark/assets/20557108/993b64e5-7c6a-41c8-8d31-58817e10d102)

Thank you very much for taking the time to answer my question.

**Comment by m-1-k-3** [comment]
Thank you for reporting. Is this on every firmware or only on selected?
@HoxhaEndri could you try to reproduce this issue please?

**Comment by BenediktMKuehne** [comment]
Hi @qingyuanyou,

about 1. 
 Do these errors still show up on the latest version?
They stem from the progress-reporter when the main-logfile is not yet written. It has no effect on the functionality, but I thought I got rid of them...

about 2
I know about this error, it's a problem with rendering problematic html-code through django.
Haven't worked on a fix/workaround yet.

The last Link problem should be easily fixable, thanks for finding and reporting.

**Comment by qingyuanyou** [comment]
Hi Team,
for the 1st one, the error fixed after git pull the latest version.
for the 2nd one,
Haven't worked on a fix/workaround yet. =>Thank you for letting me know. As there is no workaround available, I will not struggling with it. O(∩_∩)O
I have marked this issue as resolved. Thank you for your support.
