### ISSUE TITLE
Time&Date and Order question

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#161]
**Describe the bug**
On the report page in EMBArk the start and end date/time does not show the real values if the OS is not in UTC time. My timezone is CEST and I started the scanning in this timezone:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/f8b47d5e-5e49-44d2-ad56-130499abf6cc)

and according to the logs ended in correctly:
![kép](https://github.com/e-m-b-a/embark/assets/98665813/290c9a03-a42c-497c-b9b1-b97f5c8c0471)

but on the report page all the time/date values are in UTC:
![kép](https://github.com/e-m-b-a/embark/assets/98665813/77abf32b-9a68-4c15-9a47-69af9c75dea3)

Would it be possible to display the Start/End date according to the OS's time/date parameter?

********************************************

By default the ordering on the report page is by ID in ascending of the tests but in case of many runs it is not user friendly because very difficult to find the last test which may be placed on the 2nd or 3rd page in this default ordering. I know it can be easily customizable by the arrows but if I go to orther page the default ID order comes back, the user must set the custom order all the report page openings.
I think it would be more user friendly to show always the last scan on the top and the previous ones under to see always the actual results:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/70438cc2-9946-48eb-ab78-1e10317b48b9)

**To Reproduce**
1. EMBArk installation default mode
2. Start EMBArk: sudo ./run-server.sh -a <IP>
3. Do some scan
4. Check the report page behaviour.

**Expected behavior**
Like above.

**Screenshots**
Like above.

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 22.04.3

**Additional context**
These are minor findings, but if it not a big effort it would make the surface more user friendly in my point of view.

**Comment by BenediktMKuehne** [comment]
We'll try to address this in the next few weeks👍

**Comment by torabi12** [comment]
The detail view page displays the date & time in UTC also:
![image](https://github.com/e-m-b-a/embark/assets/98665813/1fe00c96-e141-4824-bb10-2baba32bb15d)

and the main page's blank frame is not so nice:
![image](https://github.com/e-m-b-a/embark/assets/98665813/e1de7110-1969-4baa-931a-e7892f2cb8d4)

and the last idea would be that the graphs like OS distribution and Architecture Distribution where the value can only be an integer, it should display only integers on the Y axis:
![image](https://github.com/e-m-b-a/embark/assets/98665813/5b6d5737-b76c-4914-8eff-e23a80da5eaf)

**Comment by BenediktMKuehne** [comment]
@torabi12 feel free to check if the changes in #164 are satisfactory

Note: The main-dashboard will get a major overhaul in the near future, that's when the timzone setting will take effect there too.

**Comment by torabi12** [comment]
Something has been changed on NIST side because this was the longest DB installation today with EMBArk setup. It took around 6 or more hours on my side, I got a warning:

"Could not find a NIST API key in the '~/.cvexplore/.env' file; you should request one at blablabla."
I have an API key, but the ~/.cvexplore/.env does not exist on my Ubuntu server. :(

Under the My Account menu the 3rd item is not visible:
![kép](https://github.com/e-m-b-a/embark/assets/98665813/61df2fee-6c17-49ba-9c9f-cde740088161)

It can be used but the readablity is simply hidden:)

I set the local time zone to Budapest:
![kép](https://github.com/e-m-b-a/embark/assets/98665813/377f1a72-86a6-4521-8727-e36656000ef8)

The green frame contained the selected value but the Time Zone selection field went back to UTC. I went to other page and back to Time zone and the UTC was shown. I did a scan and the dashboard used UTC:
![kép](https://github.com/e-m-b-a/embark/assets/98665813/fcf472d9-c571-435e-8c94-4bc83205667f)

but the log displayed the real time values:
![kép](https://github.com/e-m-b-a/embark/assets/98665813/992400a6-958a-4203-8641-3ac056d4446c)

and the same as in the detailed view:
![kép](https://github.com/e-m-b-a/embark/assets/98665813/061f5fd0-be15-47f2-a0d8-9162af74bad7)

For the scan duration, I think a time measurement based on seconds would be sufficient, smaller units are not practical, and there seems to be a few seconds difference in the length of the scan.

During the scan the time is OK for the test sections:
![kép](https://github.com/e-m-b-a/embark/assets/98665813/a5348d3b-49d5-4abe-9c8c-389103385186)

Delete analysis works fine, the main dashboard is also cleared. Maybe the Close button is unnecessary:
![kép](https://github.com/e-m-b-a/embark/assets/98665813/c1366e9d-467e-4783-b370-bfa4f416d487)

On the detailed page the Delete Firmware function is available, maybe the Delete Analysis would be also useful for user perspective:
![kép](https://github.com/e-m-b-a/embark/assets/98665813/9b917378-8481-4f1d-a8a7-e80c557d94ce)

These are my first impressions, please let me know if I can test something specific in more detail.

**Comment by m-1-k-3** [comment]
We currently switch from v1 API to v2 API from NIST and there we are running into little starting issues. See here https://github.com/e-m-b-a/emba/issues/725 and https://github.com/e-m-b-a/emba/issues/888

**Comment by m-1-k-3** [comment]
NIST issue should be fixed now https://github.com/e-m-b-a/emba/pull/899

**Comment by torabi12** [comment]
> NIST issue should be fixed now [e-m-b-a/emba#899](https://github.com/e-m-b-a/emba/pull/899)

This is on my screen right now with EMBArk installation:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/4b9df9dc-d617-473e-b678-a0016fde0088)

working.

**Comment by m-1-k-3** [comment]
I recommend to setup a NIST API key from here https://nvd.nist.gov/developers/request-an-api-key

**Comment by m-1-k-3** [comment]
Have added this to our prereq docs here https://github.com/e-m-b-a/emba/wiki/Installation#prerequisites

**Comment by torabi12** [comment]
> I recommend to setup a NIST API key from here https://nvd.nist.gov/developers/request-an-api-key

Yes I have a key, I created the ~/cvexplore folder with a .env file in it.
I cheked the beginner's guide:)
https://nvd.nist.gov/developers/start-here

and simply entered the key in this form:
apiKey:{key value}

but the yellow warnings still comes. :(

![kép](https://github.com/e-m-b-a/embark/assets/98665813/3471c502-cb7a-4046-a6af-59f654fb8e51)

I know this topic does not belong to this thread, but I have no more idea:(

**Comment by torabi12** [comment]
A did a scan which was OK, but EMBArk hangs at the end.

Finish in terminal:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/7a39ffd6-8545-4931-ba27-b80e86cee3d0)

but:
![kép](https://github.com/e-m-b-a/embark/assets/98665813/8af434a9-06b4-4432-b87a-3104b8684156)

EMBArk's console:
![kép](https://github.com/e-m-b-a/embark/assets/98665813/c4d555ee-9035-491c-9b96-45d17bed7e3d)

is hanging:
![kép](https://github.com/e-m-b-a/embark/assets/98665813/7f754b9e-5812-4898-938f-ba0b41fdb18a)

**Comment by BenediktMKuehne** [comment]
> > I recommend to setup a NIST API key from here https://nvd.nist.gov/developers/request-an-api-key
> 
> Yes I have a key, I created the ~/cvexplore folder with a .env file in it.
> I cheked the beginner's guide:)
> https://nvd.nist.gov/developers/start-here
> 
> and simply entered the key in this form:
> apiKey:{key value}
> 
> but the yellow warnings still comes. :(
> 
> ![kép](https://github.com/e-m-b-a/embark/assets/98665813/3471c502-cb7a-4046-a6af-59f654fb8e51)
> 
> I know this topic does not belong to this thread, but I have no more idea:(

Will check, might be an issue with the sudo-user var

**Comment by m-1-k-3** [comment]
This should work:
```
└─$ cat ~/.cvexplore/.env 
NVD_NIST_API_KEY=<your key>
MONGODB_HOST="172.36.0.1"
MONGODB_PORT="27017"
```

**Comment by torabi12** [comment]
> This should work:
> 
> ```
> └─$ cat ~/.cvexplore/.env 
> NVD_NIST_API_KEY=<your key>
> MONGODB_HOST="172.36.0.1"
> MONGODB_PORT="27017"
> ```

Sorry but it does not work for me:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/9641508f-247a-4898-8431-d0b42c782e34)

![kép](https://github.com/e-m-b-a/embark/assets/98665813/264cdaac-2164-4e55-a210-46b386f5ae93)

As I saw only EMBArk is affected, emba update works without this warning.

**Comment by m-1-k-3** [comment]
As quick fix could you try to add the .env file for the root user and try again?

**Comment by torabi12** [comment]
> As quick fix could you try to add the .env file for the root user and try again?

![kép](https://github.com/e-m-b-a/embark/assets/98665813/8093f82d-dffb-427e-9881-7dfd99f4cb38)

The same:(

**Comment by BenediktMKuehne** [comment]
The servers timezone can be set using the TIME_ZONE variable on startup (default UTC), like so: ` TIME_ZONE="CET" sudo -E ./run-server.sh`

**Comment by torabi12** [comment]
I started EMBArk with time_zone settings:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/162d63b2-e358-4c9d-aab4-bd6dcbc08cdd)

The actual value was displayed in the user menu:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/b648e220-ff5a-4046-98f5-4dad1e396555)

I started a scan and the times were OK:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/3af8ce43-04af-4a9e-be93-aa4e122e7a75)

but the report page displayed the times in UTC:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/4d87bd2b-5ecb-4ffb-85cd-20a8e3abd42d)

according to the log:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/56351ac9-1829-4bb6-aa83-e02fe72ffbd4)

and the details page is also shows the time in UTC:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/453ccfd8-fc18-447e-9e81-e06bcbdd4497)

I think the time and date format is not uniform.

**Comment by BenediktMKuehne** [comment]
Some parts only use the raw value inside the DB for now
If the values were put in with a different timezone setting, this leads to issues

Can't recommend using anything other than UTC for the server anyway
I'll see when I get to adjusting the rest of the dashboards

**Comment by torabi12** [comment]
I used a brand new installation yesterday on a clean Ubuntu server. This is my local time settings on OS side:
![kép](https://github.com/e-m-b-a/embark/assets/98665813/84edadf4-9171-4cf6-abed-25b245d81da9)

I started EMBArk with "UTC" parameter, the user menu displayed UTC as expected. I deleted the scan from yesterday evening and started again, it used CET here:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/5b5723ff-a244-467a-8fc1-cbc58d658989)


Test ended in CET:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/c0d3aa2a-6dd1-4fa5-9d92-2a7593eee316)

but the details were in UTC:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/02dcc5b1-c091-4ea1-8c31-1f0e6a7a4454)

![kép](https://github.com/e-m-b-a/embark/assets/98665813/22d28475-f5c3-426b-925e-91ecf04ab19b)

Actually it would be nice if the OS time setting could be applied uniformly.

**Comment by BenediktMKuehne** [comment]
I'll check and add an indicator for the servers-timezone 👍

**Comment by BenediktMKuehne** [comment]
Added some indicator and check function.
Will close this for now since I strongly recommend using UTC for host and server.

(Timezone filter will be added in the future where possible)
