### ISSUE TITLE
dashboard 302

### ISSUE THREAD

**Issue by yueqi77** [e-m-b-a/embark#167]
**Describe the bug**

Clicking on the dashboard function brings up the upload screen instead

**To Reproduce**
1. EMBArk installation (default mode/docker-mode)
2. Start EMBArk: sudo ./run-server.sh -a 
3. Scan a firmware
4. End of firmware scan，Click on the dashboard function (maybe you don't need to perform the firmware scanning task yet, after the installation is completed, you can directly open the web end to click on the dashboard function, because I only went to the dashboard to check the firmware scanning task when it was completed, and realized that it would jump to the upload interface)
5. See error

**Expected behavior**
Clicking on the dashboard function takes you to the dashboard screen and not to any other function.

**Screenshots**
![image](https://github.com/e-m-b-a/embark/assets/32604898/baee0e7b-ef14-4182-9aeb-90ef70a648eb)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS

**Additional context**

Request 302 for dashboard goes to upload, which config file should I give this to and what is the path to that file? How do I change it to make it work? Can you give me some pointers on these issues? Thank you very much!

**Comment by BenediktMKuehne** [comment]
I implemented a redirect in the case there is no finished firmware analysis yet, since the dashboard would be empty anyway.
I'll look into adding a message on redirect to make that more transparent.

**Comment by BenediktMKuehne** [comment]
How does your report-page look like when you try the link? Are there finished results?

**Comment by yueqi77** [comment]
Ohhhh, I see, because I see the logs say that the scanning has been completed, and this is a screenshot of the logs below
![image](https://github.com/e-m-b-a/embark/assets/32604898/ed746918-1014-4ad0-93ed-8e8da3408127)

Well, when the dashboard jumps all the way to upload, it reports that it's always loading, so it's only when it's in the finished state that the dashboard gets content, right?But now it seems to have failed, I've re-hung a scanning scanning task, how long before the logs show that it's completed how long will the report here be in a completed state?
![image](https://github.com/e-m-b-a/embark/assets/32604898/ae0a375f-11e3-41c8-989a-f2504b0637e1)

run_sever.sh just keeps having a warnings.warn message here, does this message cause anything substantial? For example, does it cause the status on the report side to keep loading?
![image](https://github.com/e-m-b-a/embark/assets/32604898/8c300fdc-e3f5-417b-aa84-95615970aa9b)

**Comment by yueqi77** [comment]
I didn't bother with this message anymore when I installed it and went straight to run_sever.sh, will this affect normal use? I won't be able to deal with this (loudly crying face)
![image](https://github.com/e-m-b-a/embark/assets/32604898/8728f1e8-55fa-42da-aca9-db577fb4cb8c)

**Comment by BenediktMKuehne** [comment]
> Ohhhh, I see, because I see the logs say that the scanning has been completed, and this is a screenshot of the logs below ![image](https://user-images.githubusercontent.com/32604898/285118580-ed746918-1014-4ad0-93ed-8e8da3408127.png)
> 
> Well, when the dashboard jumps all the way to upload, it reports that it's always loading, so it's only when it's in the finished state that the dashboard gets content, right?But now it seems to have failed, I've re-hung a scanning scanning task, how long before the logs show that it's completed how long will the report here be in a completed state? ![image](https://user-images.githubusercontent.com/32604898/285118146-ae0a375f-11e3-41c8-989a-f2504b0637e1.png)
> 
> run_sever.sh just keeps having a warnings.warn message here, does this message cause anything substantial? For example, does it cause the status on the report side to keep loading? ![image](https://user-images.githubusercontent.com/32604898/285119204-8c300fdc-e3f5-417b-aa84-95615970aa9b.png)

I'm seeing the same issue on one of my test-systems this morning, not sure what's going on yet, will keep you updated on that.

**Comment by BenediktMKuehne** [comment]
> I didn't bother with this message anymore when I installed it and went straight to run_sever.sh, will this affect normal use? I won't be able to deal with this (loudly crying face) ![image](https://user-images.githubusercontent.com/32604898/285120863-8728f1e8-55fa-42da-aca9-db577fb4cb8c.png)

Not sure what's going on, but the mysql db docker container or the docker interface it's on appears to not work
maybe `sudo docker-compose down && sudo docker-compose up` or a `sudo systemctl restart docker` might help.
the config seems to be fine

**Comment by yueqi77** [comment]
> > Ohhhh, I see, because I see the logs say that the scanning has been completed, and this is a screenshot of the logs below ![image](https://user-images.githubusercontent.com/32604898/285118580-ed746918-1014-4ad0-93ed-8e8da3408127.png)
> > Well, when the dashboard jumps all the way to upload, it reports that it's always loading, so it's only when it's in the finished state that the dashboard gets content, right?But now it seems to have failed, I've re-hung a scanning scanning task, how long before the logs show that it's completed how long will the report here be in a completed state? ![image](https://user-images.githubusercontent.com/32604898/285118146-ae0a375f-11e3-41c8-989a-f2504b0637e1.png)
> > run_sever.sh just keeps having a warnings.warn message here, does this message cause anything substantial? For example, does it cause the status on the report side to keep loading? ![image](https://user-images.githubusercontent.com/32604898/285119204-8c300fdc-e3f5-417b-aa84-95615970aa9b.png)
> 
> I'm seeing the same issue on one of my test-systems this morning, not sure what's going on yet, will keep you updated on that.

Okay, thank you very much!

**Comment by yueqi77** [comment]
> > I didn't bother with this message anymore when I installed it and went straight to run_sever.sh, will this affect normal use? I won't be able to deal with this (loudly crying face) ![image](https://user-images.githubusercontent.com/32604898/285120863-8728f1e8-55fa-42da-aca9-db577fb4cb8c.png)
> 
> Not sure what's going on, but the mysql db docker container or the docker interface it's on appears to not work maybe `sudo docker-compose down && sudo docker-compose up` or a `sudo systemctl restart docker` might help. the config seems to be fine

Right now it seems that only the report status side is problematic because it keeps loading, maybe it takes time, I'm waiting for more than 1 hour without a new status update like failed or completed, I'll try the command you posted and restart again!

**Comment by BenediktMKuehne** [comment]
Testing a fix right now
