### ISSUE TITLE
Automatically guessing the base address of a firmware image

### ISSUE THREAD

**Issue by Moneysac90** [e-m-b-a/embark#174]
When trying to reverse engineer a firmware image with ghidra or IDA Pro you often have to specify the base address in order to decompile the code correctly. 

There are some tools that try to guess the correct base address. For example:

- https://github.com/quarkslab/binbloom
- https://github.com/soyersoyer/basefind2

We could add such scripts as additionally checks and provide a separate tab/overview of the possible base addresses. Furthermore, it would be awesome if we could have a download button somewhere in Embark to download the extracted files. 
This simplifies the process of reverse engineering because you can directly analyze them with your favorite disassembler/decompiler.

**Comment by m-1-k-3** [comment]
This probably could be interesting for RTOS systems. If we detect an RTOS, the next step usually is to find the base address for further analysis.

**Comment by BenediktMKuehne** [comment]
A resource download function exists, there is just no button/interface for it yet.
Right now for that purpose we use the Download-Logs funktion instead.

Will look into this.
(Might also require some EMBA changes to what gets put and kept in the log-directory)

**Comment by m-1-k-3** [comment]
I think this issue would better fit in the EMBA backend. If needed please re-open it here https://github.com/e-m-b-a/emba/issues
