### ISSUE TITLE
NVD list is running on the screen

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#175]
**Describe the bug**
I started EMBArk as
`$ TIME_ZONE="CET" sudo -E ./run-server.sh -a <IP>`

and after the initialization the nvd list was running for 3 minutes on the screen:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/ef8a7f2a-b12a-472d-81a0-83de7e523e10)

Maybe it is ok but it has never been displayed.

Another minor issue is that I wanted to use my AI API key, which is valid, but EMBArk faild to use it and this was displayed many times:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/ffced0d3-a8ec-4df4-88f2-c8a0929f32ef)

**To Reproduce**
1. EMBArk installation (default mode)
2. Start EMBArk: sudo ./run-server.sh -a IP
3. See the output

OS: Ubuntu Server 22.04.3

**Comment by BenediktMKuehne** [comment]
I haven't used the openai api key in EMBArk yet, but that particular error would indicate a problem with the api key

When you say it's valid, is it working somewhere else?(e.g curl directly)

The NVD output is a sync between the actual submodule directory and the one used by the server. (just as an explanation)
Will see what's the issue is

**Comment by torabi12** [comment]
I exceeded my quota with the key, please ignore this screenshot.
I just wanted to share the running nvd section, which takes some time when I start EMBArk, but it goes fine at the end.

**Comment by torabi12** [comment]
Sorry, but the nvd list is running for 5 minutes during EMBArk initialization:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/af4020dd-19a2-4b1d-bbf8-04c93fcb0e67)

It is not critical but I can't see any difference. May it is good as it is just a bit of a surprise to wait.

**Comment by BenediktMKuehne** [comment]
Current sync operation is the fastest, i checked

It's due to a lot of separate files on initial copy
