### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#178]
**Describe the bug**
I started a default installation but it dropped an error and after that exited.

**To Reproduce**
1. EMBArk installation (default mode)
2. See error

**Screenshots**
![kép](https://github.com/e-m-b-a/embark/assets/98665813/b599ba82-5741-49cf-ab31-ad82f5ab9c6f)

![kép](https://github.com/e-m-b-a/embark/assets/98665813/2e30b7a4-e30d-44a4-8604-fc5e6602897d)

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 22.03.4

**Comment by m-1-k-3** [comment]
Do you have a very new docker version running?
Could you please give us some version details:
```
pip3 list | grep docker
dpkg -l | grep docker
```
This error is also shown here https://github.com/docker/docker-py/issues/3194

**Comment by torabi12** [comment]
> Do you have a very new docker version running? Could you please give us some version details:
> 
> ```
> pip3 list | grep docker
> dpkg -l | grep docker
> ```
> 
> This error is also shown here [docker/docker-py#3194](https://github.com/docker/docker-py/issues/3194)

Yes, it is an updated Ubuntu server:
![kép](https://github.com/e-m-b-a/embark/assets/98665813/e149d395-d9c1-46f7-95dd-ed8bcdae070f)

**Comment by m-1-k-3** [comment]
docker 7.0.0 breaks currently a lot ... please downgrade to <7.0.0

**Comment by torabi12** [comment]
I see, but pip3 and docker comes with the emba installation.

**Comment by torabi12** [comment]
This way it is working:
![kép](https://github.com/e-m-b-a/embark/assets/98665813/6521d2e8-724e-4e8c-9d9a-a831aa90d1cb)

Would it be possible to use the suitable package in the installer?

**Comment by torabi12** [comment]
Sorry, but this fix fdid not solve the problem. The clean Ubuntu server does not have python and docker installed.
The emba(rk) installation downloads the 7.0.0 package and the installer fails again:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/581e5cfe-2b3c-4aae-9aaf-8ba8d2a25cbe)

and a few seconds later:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/480a7ec7-1b00-4b80-83a5-344c33dfeab7)

If I install manually the good version the installer works fine, but the installer alone does not work:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/fe1e692b-2d31-485b-80bd-603a8c094830)

**Comment by torabi12** [comment]
I installed docker 6.1.3 manually on a clean Ubbuntu and after that the installer also failed.

**Comment by BenediktMKuehne** [comment]
There were some breaking changes to docker(-compose)
Working on resolving this.

Docker version <7.0.0 set for root worked yesterday, i'll look into it

**Comment by torabi12** [comment]
I took a new clean up to date Ubuntu Server 22.04.3 and I installed manually these:

```
$ sudo apt install python3-pip
$ sudo pip3 install docker==6.1.3
```

reboot, and EMBArk installer:

`$ sudo ./installer.sh -d | tee install.txt`

please check the output lines 547-553:

[install.txt](https://github.com/e-m-b-a/embark/files/13657363/install.txt)

**Comment by m-1-k-3** [comment]
over night I did a fresh installation on Ubuntu Server 22.04.3 and got these installed:

![image](https://github.com/e-m-b-a/embark/assets/497520/4efb3d48-8454-4259-93e2-4449f50c1c2b)

**Comment by torabi12** [comment]
> over night I did a fresh installation on Ubuntu Server 22.04.3 and got these installed:
> 
> ![image](https://private-user-images.githubusercontent.com/497520/290105725-4efb3d48-8454-4259-93e2-4449f50c1c2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTE5ODMsIm5iZiI6MTcwMjQ1MTY4MywicGF0aCI6Ii80OTc1MjAvMjkwMTA1NzI1LTRlZmIzZDQ4LTg0NTQtNDI1OS05M2UyLTQ0NDlmNTBjMWMyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwNzE0NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjNlNzI3ZWJkZDJhNjlhZmFjYjJkN2UzNGI5YTdjMWY5YzIzMjgxMDI2ZDc0NWViNTdiMWExMjVmMmFiOTg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9FQ2YVdHnk5WLVTXdelpz_3Ww4ln2y9V_m1C_6EcLVM)

I am using hu.archive.ubuntu.com for apt.
If I use clean OS emba(rk) will download docker 7.0.0

![kép](https://github.com/e-m-b-a/embark/assets/98665813/57f86f38-f23f-45c2-8364-76515f8ea0eb)

but if I install manually 6.1.3 it is not OK after the last update. Yesterday when I tried it before the fix it was working with 6.1.3 for me.

**Comment by m-1-k-3** [comment]
According to https://packages.ubuntu.com/jammy/allpackages version 5.0.3 gets installed. I do not understand how you got v7.0.0. Please give us more details on how we can reproduce this issue in detail. Currently we support Ubuntu 22.04 with the usually installed packages and I am wondering on how a LTS version can automatically go up to docker 7. Docker v7 will be supported in the future but not yet

**Comment by torabi12** [comment]
Thank you, I deleted my VM and started again following this process with a band new VM from ubuntu.com:)

ubuntu-22.04.3-live-server-amd64.iso

At the beginning of the installation I upgraded to the new installer.

Used mirror:
http://hu.archive.ubuntu.com/ubuntu/

Ubuntu Pro skipped

SSH installed.
I add this line to GRUB to have better resolution:
`GRUB_GFXPAYLOAD_LINUX=1152x864`

reboot

```
$ sudo timedatectl set-timezone Europe/Budapest
$ sudo apt update
$ sudo apt upgrade -y
```

reboot

`$ git clone https://github.com/danielmiessler/SecLists.git`

`$ touch module_blacklist.txt`
S99_grepit
S110_yara_check

I have this:
Linux embark 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Shutdown & Snapshot

```
$ git clone https://github.com/e-m-b-a/embark.git
$ sudo ./installer.sh -d | tee new_install.txt
```

This is the error in the installer at the end:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/40339507-4f04-4137-ab85-870779d37830)

I don't know why, but I got 7.0.0. By default the OS did not contain any docker or python version before emba(rk) installation.

[new_install.txt](https://github.com/e-m-b-a/embark/files/13658247/new_install.txt)

Please check lines 1549-1559 and the last few lines.

I can go back to the snapshot any time to try again.

**Comment by m-1-k-3** [comment]
@torabi12 could you please test an EMBA installation with the linked PR?

**Comment by torabi12** [comment]
I did it on a Kali VM:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/827b944c-ecf3-4cd7-8b98-cf94fcc75fcc)

There was no error during the installation! :)

**Comment by m-1-k-3** [comment]
> I did it on a Kali VM:
> 
> There was no error during the installation! :)

and on your special Ubuntu?

**Comment by torabi12** [comment]
![kép](https://github.com/e-m-b-a/embark/assets/98665813/df2ce2d4-6d59-4cc3-a14c-3c028c84d69a)

on Ubuntu it asks for pass. :(

**Comment by m-1-k-3** [comment]
you got the wrong URL .... should be m-1-k-3

**Comment by torabi12** [comment]
It was also working on Ubuntu server:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/8b5d0a4d-5afb-4da4-98d8-804fa246e5d0)

sorry for the typo. Ubuntu's terminal needs typing. :(

**Comment by torabi12** [comment]
Installer works fine:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/0df758e4-7bc7-4e4e-81e3-03c4a3215772)

EMBArk can be started:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/85d5bd09-e389-4f49-89aa-3dd1d53ef427)

Thank you for your support!

**Comment by m-1-k-3** [comment]
Thanks for pointing us to this issue. Keep on finding bugs ;)
