### ISSUE TITLE
s109 drops 500 in report

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#183]
**Describe the bug**
I did a short scan and "Cracking identified password hashes" menu dropped 500 in the browser. The s109_jtr_local_pw_cracking.html exists in the file system and contains the good password. Only the page is not displayed.

**To Reproduce**
1. EMBArk installation (default mode)
2. Start EMBArk: sudo ./run-server.sh
3. Use the firmware available here: kkeps.bin
4. Open Cracking identified password hashes menu in detailed view.
5. See error

**Expected behavior**
Display page for s109.

**Screenshots**
![kép](https://github.com/e-m-b-a/embark/assets/98665813/1fc1f233-da20-4e3b-b4ca-58c87055943e)

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 22.04.3

**Additional context**
[s109_jtr_local_pw_cracking.txt](https://github.com/e-m-b-a/embark/files/13664247/s109_jtr_local_pw_cracking.txt)

**Comment by BenediktMKuehne** [comment]
I would guess it's a non utf8 conform byte that causes the issue.

Can you:
1. Supply me with the actual html-report folder (alternatively, just the html file that's not working)
2. Check for log errors for a Unicodedecode error

**Comment by torabi12** [comment]
[html-report.zip](https://github.com/e-m-b-a/embark/files/13664633/html-report.zip)
[emba_run.log](https://github.com/e-m-b-a/embark/files/13664635/emba_run.log)

There are more log files, I don't know which one should I check. :(

Lines in emba_run.log with (Bad file descriptor) are very strange because of the huge repetitions. But it is not connecting to http 500 I believe.

**Comment by BenediktMKuehne** [comment]
Sorry, `/var/www/embark/embark.log`

**Comment by torabi12** [comment]
[embark.log](https://github.com/e-m-b-a/embark/files/13664869/embark.log)

Yes, UnicodeDecodeError exists more times in the file:(

**Comment by BenediktMKuehne** [comment]
Will try to solve this in EMBA directly

**Comment by BenediktMKuehne** [comment]
@torabi12 could you provide me with the firmware for testing?

**Comment by torabi12** [comment]
Please download it from here:

https://drive.google.com/file/d/1jXqPpg_z8ghZG0XPxtx-qtl2Mx_N2FL1/view?usp=sharing

I used Top109Million-probable-v2.txt as jtr_wordlist.txt from here:

https://github.com/berzerk0/Probable-Wordlists/tree/master/Real-Passwords

and I added manually the good password at the end of the file.

This is the password file:

https://drive.google.com/file/d/11q3ARlr9fL4Fh_hqrUFXTfG-xbOw_6oD/view?usp=sharing

You should add the "p9z34c" value at the end and emba will find it, if you would like to reproduce the whole test from my side.

**Comment by torabi12** [comment]
It can happen that I used a not supported password file and that caused this issue. I am going to try the same test with a basic password list and let you know the outcome soon.

**Comment by torabi12** [comment]
Hmm, I used rockyou.txt with adding the good password to the last line and the s109 cracked it and the page is available:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/0112241f-f8f5-4825-aa99-0a20e049a179)

Looks like I used a not supported password list. :(
I just wanted to have a huge dictionary for better coverage. My last question would be if you could suggest any good and large list it would be great but I will also look for an acceptable one.

**Comment by torabi12** [comment]
I tried today and the page is available:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/dd7009aa-3941-49af-8f63-01b3577a27bf)

Thank you!

**Comment by m-1-k-3** [comment]
@BenediktMKuehne good work

**Comment by BenediktMKuehne** [comment]
The changes affect only s109  and s99 (jtr and grepit modules)
