### ISSUE TITLE
What is the maximum size for uploading firmware

### ISSUE THREAD

**Issue by spon94** [e-m-b-a/embark#189]
**Describe the bug**
I can’t up load the firmware successfully > 2GB

**To Reproduce**
1. EMBArk installation (default mode/docker-mode)
2. Start EMBArk: sudo ./run-server.sh
3. Use the firmware available here: <Insert URL>
4. Select the target firmware > 2GB,
5. The progress bar is stuck

**Expected behavior**
Upload it successfully.
I'm wondering the maximum size for uploading firmware

**Comment by BenediktMKuehne** [comment]
[https://github.com/e-m-b-a/embark/blob/main/run-server.sh#L28](https://github.com/e-m-b-a/embark/blob/main/run-server.sh#L28)
Has the max file size for post requests going through the wsgi. Default is 2GiB yes

**Comment by spon94** [comment]
Thanks！
