### ISSUE TITLE
question : Enabling GPU processing with EMBA and EMBArk

### ISSUE THREAD

**Issue by Lynn-TX** [e-m-b-a/embark#190]
I just installed a fresh Ubuntu 22.04.3 LTS load with an NVIDIA Corporation TU104GL [Quadro RTX 4000] and the lasted EMBArk clone, but I have not been able to find any documentation via the wiki or discussions on how to enable EMBArk/EMBA to leverage the GPU's. 

If anyone could: 
1) Validate that EMBArk/EMBA can leverage GPU's? 
2) Point me to a URL or other documentation that notes how to enable GPU processing within EMBArk/EMBA. 

Thank you for your help.

**Comment by BenediktMKuehne** [comment]
To my knowledge, the only module that might support GPU usage would be S109 ( jtr).
But currently there is no implementation for that.

**Comment by m-1-k-3** [comment]
Currently there is no GPU support in EMBA.

**Comment by Lynn-TX** [comment]
BenediktMKuehne and M-1-k-3.... 

Thank you for responding to my post, you saved me a bunch of time trying to implement GPU's.
