### ISSUE TITLE
emba updates available message

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#193]
**Describe the bug**
After installing the latest EMBArk/emba environment I started EMBArk and the message was displayed:
"EMBA github version - Updates available"

**To Reproduce**
1. EMBArk installation (default mode)
2. Start EMBArk: sudo ./run-server.sh -a IP
3. See "Dependeny check" messages

**Expected behavior**
Should be OK, if a new environment is installed on a clean Ubuntu server.

**Screenshots**
![kép](https://github.com/e-m-b-a/embark/assets/98665813/ca97aa3d-a7e7-423d-8350-bbbd78d1bdbc)

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 22.04.3

**Comment by m-1-k-3** [comment]
the job in backend is now running every 5 mins. Should be solved now

**Comment by m-1-k-3** [comment]
ok, there is another bug in the version checking ... will check this now

**Comment by torabi12** [comment]
In case of fully offline system I got this:
![image](https://github.com/e-m-b-a/embark/assets/98665813/0d214876-7218-4732-9ac0-90e91f455590)

and with PROXY usage I got this a few minutes before:
![image](https://github.com/e-m-b-a/embark/assets/98665813/be65592c-b07c-446e-aa0e-9c94ddc0bd89)

Will check later again....

**Comment by m-1-k-3** [comment]
> In case of fully offline system I got this: ![image](https://private-user-images.githubusercontent.com/98665813/308087593-0d214876-7218-4732-9ac0-90e91f455590.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjQ0MDYsIm5iZiI6MTcwOTAyNDEwNiwicGF0aCI6Ii85ODY2NTgxMy8zMDgwODc1OTMtMGQyMTQ4NzYtNzIxOC00NzMyLTlhYzAtOTBlOTFmNDU1NTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA4NTUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNDliMjRhMmMwNjM2MTdjZDBiZDJjOWEzYzU3YzIxZjIxOGQ3Zjk4NWJhZjI5MGI1NzIwOWU2NGQzZjJlYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dRN-YWCvB7NhYyauuKUOZ4PcuEhQEK3dbgdxA6vDhcc)
> 
Without Internet the update check will fail and you will not get notes on available updates

**Comment by torabi12** [comment]
> > In case of fully offline system I got this: ![image](https://private-user-images.githubusercontent.com/98665813/308087593-0d214876-7218-4732-9ac0-90e91f455590.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjQ0MDYsIm5iZiI6MTcwOTAyNDEwNiwicGF0aCI6Ii85ODY2NTgxMy8zMDgwODc1OTMtMGQyMTQ4NzYtNzIxOC00NzMyLTlhYzAtOTBlOTFmNDU1NTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA4NTUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNDliMjRhMmMwNjM2MTdjZDBiZDJjOWEzYzU3YzIxZjIxOGQ3Zjk4NWJhZjI5MGI1NzIwOWU2NGQzZjJlYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dRN-YWCvB7NhYyauuKUOZ4PcuEhQEK3dbgdxA6vDhcc)
> 
> Without Internet the update check will fail and you will not get notes on available updates

Yes, it's OK, just wanted to show you the outcome.
