### ISSUE TITLE
emba update does not work under EMBArk

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#199]
**Describe the bug**
I used ./emba -U under Kali&emba and it works fine:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/85510515-2f71-40d7-9a46-39e10dab7b04)

Running the same command on Ubuntu&EMBArk (embark/emba) I get an error:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/3a9d95a6-9b91-497d-9e49-8f4f2c8f2019)

**To Reproduce**
1. EMBArk installation default mode
2. `cd embark/emba`
3. `sudo ./emba -U`

**Expected behavior**
Update should also work under EMBArk.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Kali Linux 2024.1 & Ubuntu Server 22.04.4

**Comment by farmmanic** [comment]
have you tried sudo git submodule update --remote --merge

**Comment by torabi12** [comment]
> have you tried sudo git submodule update --remote --merge

Thank you., this command solves my problem:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/fecea227-de86-4f26-b6c0-5c5ea35653b0)

`sudo ./emba -U`

![kép](https://github.com/e-m-b-a/embark/assets/98665813/177df5c2-0560-4280-bdd3-68935da0b62d)

**Comment by BenediktMKuehne** [comment]
Still working on the update functionality in the web interface
in the future we'll have a simple button
