### ISSUE TITLE
S16 drops error code 500

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#205]
**Describe the bug**
I opened the identified source function links under S16 and I got 500 in the browser.

**To Reproduce**
1. EMBArk installation default mode
2. Start EMBArk: sudo ./run-server.sh
3. Use the firmware available here: http://legacyfiles.us.dlink.com/DIR-601/REVB/FIRMWARE/DIR-601_REVB_FIRMWARE_2.01.ZIP
4. Wait for the test results.
5. Check s16 links.
6. See error

**Expected behavior**
The link should open the c file, which is available in the filesystem:

/var/www/emba_logs/42a3b9f4-9557-43eb-9063-0a74de9f1c23/emba_logs/s16_ghidra_decompile_checks/haruspex_libputil.so/char_token_00010da0.c

**Screenshots**
![kép](https://github.com/e-m-b-a/embark/assets/98665813/c352b698-7a3a-4a1a-aa05-ba60a7c917b8)

![kép](https://github.com/e-m-b-a/embark/assets/98665813/827da90a-a53b-405d-94c0-2f0b800592f3)

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 22.04.4

**Comment by torabi12** [comment]
I checked the same scenario in emba and it is ok there:

![kép](https://github.com/e-m-b-a/embark/assets/98665813/4cfac82f-cbbd-4e3f-972f-8cb30f8eb086)

**Comment by BenediktMKuehne** [comment]
#209
