### ISSUE TITLE
emba update available

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#206]
**Describe the bug**
Tried the EMBArk installation with the new 1.4.1 emba and worked fine. The dependency check drops update available for emba when I start EMBArk or I just run
`$ sudo emba -d 1`

A warning is diplayed for docker-compose.yml file.

**To Reproduce**
1. EMBArk installation docker-mode
2. Start EMBArk: sudo ./run-server.sh
3. or just check dependecies for emba
4. See the yellow warnings.

**Expected behavior**
`$ sudo ./emba -V` displayed 1.4.1 and the environment works fine.

**Screenshots**
![kép](https://github.com/e-m-b-a/embark/assets/98665813/f6053597-125b-4bb9-8212-f8b215212c42)

![kép](https://github.com/e-m-b-a/embark/assets/98665813/481a8297-299a-4f1d-a89f-8df2a6bf7ca0)

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 22.04.4

**Additional context**
Please ignore this question if it is not relevant.

**Comment by torabi12** [comment]
The same on emba side, this does not belomng to EMBArk.

**Comment by torabi12** [comment]
I did something wrong, it works fine.

![kép](https://github.com/e-m-b-a/embark/assets/98665813/3965f5ee-9c7b-4b56-b3a3-4c13c1cc34f2)

**Comment by m-1-k-3** [comment]
enjoy teh new release :)
