### ISSUE TITLE
Server Error without Label Name

### ISSUE THREAD

**Issue by D4n1ng** [e-m-b-a/embark#208]
When setting up firmware to analyze and not setting a label name the tool is not capable of analyzing. It redirects to embark.local/uploader/start/ and gives a Server Error (500). The logs revealed it is due to not having a label name given. 
When given a label name it worked properly again.

1. EMBArk installation (default mode/docker-mode)
2. Start EMBArk: sudo ./run-server.sh
3. Use the firmware available here: (https://www.tp-link.com/de/support/download/tl-wr802n/#Firmware)
4. Upload Firmware
5. Add new Vendor
6. Define the device-under-test
7. Analyze (with Firmwareversion added)
8. See error

**Expected behavior**
After setting up the tool should redirect to the embark.local/dashboard/service page after the analyze button was clicked.

 - OS: Ubuntu 22.04.4 Jammy Jellyfish

The other variant seen on the screenshot called test had a label name and worked fine.

Screenshots

![image](https://github.com/e-m-b-a/embark/assets/145357956/6f748c76-4a1f-49b9-a2db-5d5e48f7d4c4)
![image](https://github.com/e-m-b-a/embark/assets/145357956/820be5ca-e8ec-44af-9d2e-4c27a9a2128a)
![image](https://github.com/e-m-b-a/embark/assets/145357956/b9df3851-cb78-4cc6-b3c7-c8353e08480e)

**Comment by torabi12** [comment]
I repeated your steps and I got the same 500 error.
When I did not select the device category:
![kép](https://github.com/e-m-b-a/embark/assets/98665813/4d7312f8-ba6c-4cb6-b497-5f356b75aded)

the test is started as expected:
![kép](https://github.com/e-m-b-a/embark/assets/98665813/c001ee57-335d-4ac4-bb8e-6711125b2557)
