### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#213]
**Describe the bug**
The dependency check fails during the installation.

**To Reproduce**
1. EMBArk installation default mode
2. See error

**Expected behavior**
Should go on like emba installation on Kali.

**Screenshots**
![kép](https://github.com/user-attachments/assets/64c76ea5-3d64-477c-ba7b-6d82865823ce)

**Desktop (please complete the following information):**
 - OS: Ubuntu Server x64 22.04.4 LTS

**Comment by moritzan** [comment]
We've had the same issue when installing Embark on our Ubuntu 22.04 machines.
a temporary fix was installing docker-compose manually (https://docs.docker.com/compose/install/linux/) and re running the Embark installation.

**Comment by m-1-k-3** [comment]
@BenediktMKuehne could you take over. I think this was an EMBA issue which schould be already addressed here https://github.com/e-m-b-a/emba/issues/1247

**Comment by BenediktMKuehne** [comment]
Will take care of it asap

**Comment by BenediktMKuehne** [comment]
Should be fixed

**Comment by torabi12** [comment]
Sorry but it was not OK for me:

![kép](https://github.com/user-attachments/assets/fe9ffb0a-462f-4508-83a1-9cfb4aadf447)

I am going to try again later, maybe my connection was not fine because it was very slow during the install.

Looks like the local mirror is not the best:

![kép](https://github.com/user-attachments/assets/fafe5af7-9327-4fe9-abbb-f8999dcf5007)

**Comment by torabi12** [comment]
The install contains a lot of this errors:

```
 Cannot initiate the connection to hu.archive.ubuntu.com:80 (2a09:7ac0::4). - connect (101: Network is unreachable) Could not connect to hu.archive.ubuntu.com:80 (45.67.159.244), connection timed out
Err:8 http://hu.archive.ubuntu.com/ubuntu jammy/main amd64 rpcsvc-proto amd64 1.4.2-0ubuntu6
  Cannot initiate the connection to hu.archive.ubuntu.com:80 (2a09:7ac0::4). - connect (101: Network is unreachable)
Ign:9 http://hu.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libtirpc-dev amd64 1.3.2-2ubuntu0.1
Err:10 http://hu.archive.ubuntu.com/ubuntu jammy/main amd64 libnsl-dev amd64 1.3.0-2build2
  Cannot initiate the connection to hu.archive.ubuntu.com:80 (2a09:7ac0::4). - connect (101: Network is unreachable)
Ign:11 http://hu.archive.ubuntu.com/ubuntu jammy-updates/main amd64 gcc-11-base amd64 11.4.0-1ubuntu1~22.04
Err:12 http://hu.archive.ubuntu.com/ubuntu jammy/main amd64 libisl23 amd64 0.24-2build1
  Cannot initiate the connection to hu.archive.ubuntu.com:80 (2a09:7ac0::4). - connect (101: Network is unreachable)
Err:13 http://hu.archive.ubuntu.com/ubuntu jammy/main amd64 libmpc3 amd64 1.2.1-2build1
  Cannot initiate the connection to hu.archive.ubuntu.com:80 (2a09:7ac0::4). - connect (101: Network is unreachable)
Ign:14 http://hu.archive.ubuntu.com/ubuntu jammy-updates/main amd64 cpp-11 amd64 11.4.0-1ubuntu1~22.04
Err:15 http://hu.archive.ubuntu.com/ubuntu jammy/main amd64 cpp amd64 4:11.2.0-1ubuntu1
  Cannot initiate the connection to hu.archive.ubuntu.com:80 (2a09:7ac0::4). - connect (101: Network is unreachable)
```

**Comment by torabi12** [comment]
Good news is that on Kali emba install works fine. Only Ubuntu and EMBArk is wrong now.

**Comment by m-1-k-3** [comment]
> The install contains a lot of this errors:
> 
> ```
>  Cannot initiate the connection to hu.archive.ubuntu.com:80 (2a09:7ac0::4). - connect (101: Network is unreachable) Could not connect to hu.archive.ubuntu.com:80 (45.67.159.244), connection timed out
> Err:8 http://hu.archive.ubuntu.com/ubuntu jammy/main amd64 rpcsvc-proto amd64 1.4.2-0ubuntu6
>   Cannot initiate the connection to hu.archive.ubuntu.com:80 (2a09:7ac0::4). - connect (101: Network is unreachable)
> Ign:9 http://hu.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libtirpc-dev amd64 1.3.2-2ubuntu0.1
> Err:10 http://hu.archive.ubuntu.com/ubuntu jammy/main amd64 libnsl-dev amd64 1.3.0-2build2
>   Cannot initiate the connection to hu.archive.ubuntu.com:80 (2a09:7ac0::4). - connect (101: Network is unreachable)
> Ign:11 http://hu.archive.ubuntu.com/ubuntu jammy-updates/main amd64 gcc-11-base amd64 11.4.0-1ubuntu1~22.04
> Err:12 http://hu.archive.ubuntu.com/ubuntu jammy/main amd64 libisl23 amd64 0.24-2build1
>   Cannot initiate the connection to hu.archive.ubuntu.com:80 (2a09:7ac0::4). - connect (101: Network is unreachable)
> Err:13 http://hu.archive.ubuntu.com/ubuntu jammy/main amd64 libmpc3 amd64 1.2.1-2build1
>   Cannot initiate the connection to hu.archive.ubuntu.com:80 (2a09:7ac0::4). - connect (101: Network is unreachable)
> Ign:14 http://hu.archive.ubuntu.com/ubuntu jammy-updates/main amd64 cpp-11 amd64 11.4.0-1ubuntu1~22.04
> Err:15 http://hu.archive.ubuntu.com/ubuntu jammy/main amd64 cpp amd64 4:11.2.0-1ubuntu1
>   Cannot initiate the connection to hu.archive.ubuntu.com:80 (2a09:7ac0::4). - connect (101: Network is unreachable)
> ```

looks as you have connection issues

**Comment by torabi12** [comment]
Yes, a simple
`$ sudo apt update`
is not ok now, sorry.

Tomorrow I will create a brand new Ubuntu VM and try again. I think my VM has issues now. :(

![kép](https://github.com/user-attachments/assets/1107d88f-808f-478b-ab84-85e493161f77)

**Comment by torabi12** [comment]
So, I created a new VM with official Ubuntu Server 22.04.4 LTS. apt update / upgrade works fine:

![kép](https://github.com/user-attachments/assets/27eee105-79c7-4348-b18b-67626fff8c65)

Tried again the EMBArk installer and I got back the original issue:

![kép](https://github.com/user-attachments/assets/871df203-e340-4827-bdd3-02ca4c3f1ec4)

All is good except the docker-compose. :(

**Comment by m-1-k-3** [comment]
EMBA Installation also failed tonight. Need to check this

**Comment by torabi12** [comment]
> EMBA Installation also failed tonight. Need to check this

Thank you.

**Comment by m-1-k-3** [comment]
On Kali EMBA installs fine. Next, i need to check on Ubuntu

**Comment by m-1-k-3** [comment]
Please test https://github.com/e-m-b-a/emba/pull/1260

**Comment by torabi12** [comment]
I tried on Kali and Ubuntu and both were working fine:

![kép](https://github.com/user-attachments/assets/01c118b6-e311-40ac-85e4-9cc45754bda4)
