### ISSUE TITLE
mysql and redis docker images issue

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#216]
**Describe the bug**
EMBArk installation at this point I was waiting a few minutes:

![kép](https://github.com/user-attachments/assets/052b1fcc-3178-49d9-90dc-5ec22e51de11)

and I got this error:

![kép](https://github.com/user-attachments/assets/53a0bc60-3071-4eb4-adbb-1bfae4e7ca51)

Tried 2 times with same results.

**To Reproduce**
1. EMBArk installation default mode
2. See error

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS

**Comment by BenediktMKuehne** [comment]
We had to migrate to the compose plugin for docker.

The installer installs it automatically.
For older installations, I would recommend uninstalling the old `docker-compose` and installing the new.
[Install docker compose](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository)

**Comment by torabi12** [comment]
I did the manual installation and it works now. Thank you.

**Comment by BenediktMKuehne** [comment]
Sorry for the inconvenience...docker really is the worst dependency we have so far 😅
