### ISSUE TITLE
Failed Embark Install

### ISSUE THREAD

**Issue by DRG-pi** [e-m-b-a/embark#220]
**Describe the bug**
A fresh install of Embark using "git clone https://github.com/e-m-b-a/embark.git; cd embark; sudo ./installer.sh -d"
fails with 

"Creating a EMBArk configuration file .env
docker: 'compose' is not a docker command.
See 'docker --help'
unknown shorthand flag: 'd' in -d
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND
"
1. checking startup

unknown shorthand flag: 'f' in -f
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

**To Reproduce**
1. Download and install Ubuntu 22.04.5 LTS
2. Execute "git clone https://github.com/e-m-b-a/embark.git; cd embark; sudo ./installer.sh -d"
3. Check log output

**Expected behavior**
I expected Embark to be installed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.5 LTS

**Additional context**
Was a Fresh Ubuntu install

**Comment by BenediktMKuehne** [comment]
The installation of the compose plugin must have failed somewhere at the beginning of the installation.

Can you provide the complete output of the installation?

**Comment by torabi12** [comment]
This is the failure in the install:
![kép](https://github.com/user-attachments/assets/ae08db00-9f44-46c9-ae76-cefb1fbfe5d7)

The full log from the terminal:
[install.txt](https://github.com/user-attachments/files/17215423/install.txt)

**Comment by BenediktMKuehne** [comment]
That's weird, the log shows it's pulling the compose plugin from source.

Will have a fix here soon.
As a work around you could do [this](https://github.com/e-m-b-a/embark/blob/main/installer.sh#) -line 261-manually

**Comment by BenediktMKuehne** [comment]
EMBA now also installs the new docker versions, which should fix the issue.

**Comment by jwierzch** [comment]
I have had the same issue , reverting to commit 347ba8d8f08dc5b684ea11153ca08d9f2d1cba2 worked to install. I am troubleshooting further. 
so running checkout before running the install ...
`git checkout 347ba8d8f08dc5b684ea11153ca08d9f2d1cba2`

of note commit dd5d6c5d29fc549ad53baaed05ad96e063a82d1f installs but shows forbidden when trying to access the server page , and current commit doesn't install at all per op posting.

**Comment by BenediktMKuehne** [comment]
> I have had the same issue , reverting to commit [347ba8d](https://github.com/e-m-b-a/embark/commit/347ba8d8f08dc5b684ea11153ca08d9f2d1cba28) worked to install. I am troubleshooting further. so running checkout before running the install ... `git checkout 347ba8d8f08dc5b684ea11153ca08d9f2d1cba2`
> 
> of note commit [dd5d6c5](https://github.com/e-m-b-a/embark/commit/dd5d6c5d29fc549ad53baaed05ad96e063a82d1f) installs but shows forbidden when trying to access the server page , and current commit doesn't install at all per op posting.

did you add the host IP-address as an alias when starting the server?

Also this docker problem was addressed in EMBA directly, please open separate issue if needed
