### ISSUE TITLE
WS/ASGI “no route found for path”

### ISSUE THREAD

**Issue by secsonthebeach** [e-m-b-a/embark#221]
Hello,

The websocket connection seems to be broken. I keep seeing the error mentioned above.

I notice that `embark/embark/routing.py` mentions being the equivalent of `urls.py` but it is not the same.

`embark/embark/urls.py` shows the inclusion of `embark/reporter/urls.py` which then contains the variable `EMBA_LOG_URL` containing the proper file location. Is this missing from ASGI?

I cannot otherwise seem to find where the file location is being passed to Daphne when executing `run-server.sh`.

Please let me know what you think.

**Comment by BenediktMKuehne** [comment]
Sorry I only saw this now.

I recognize this from some issues with the contents of the log-directory
If you find some content you can not access while clicking through the html report, you could mark the request here and I'll try and adjust the routing

**Comment by secsonthebeach** [comment]
I have not had trouble viewing the HTML report by going to the  “Reports” and selecting it from the drop down menu. Similarly, I can view the “raw log”.

The problem I am seeing is with the websockets (I think). I can’t be sure, because this is all my first time with Embark, but I think the expected behavior is a live stream of `/ws/progress` from the “Progress” UI tab, or a live stream of the logging data `/ws/logs/<id>` from the “Reports -> View Log” UI.

In my case, every call to a websocket returns an error message of “No route found for path”.

I think my initial question may have misguided, but I do think the issue lies within Daphne and the application passed to it, and the ASGI stuff.

Also, I removed and reinstalled yesterday, just to ensure that I hadn’t made some change that introduced the error.

Below is the error output observed from `run-server.sh` when a websocket connection is attempted:

```
2024-10-22 15:36:56,106 ERROR Exception inside application: No route found for path '/ws/progress/'.
Traceback (most recent call last):
  File "/var/www/.venv/lib/python3.10/site-packages/channels/routing.py", line 62, in __call__
    return await application(scope, receive, send)
  File "/var/www/.venv/lib/python3.10/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/var/www/.venv/lib/python3.10/site-packages/channels/sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/var/www/.venv/lib/python3.10/site-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "/var/www/.venv/lib/python3.10/site-packages/channels/middleware.py", line 24, in __call__
    return await self.inner(scope, receive, send)
  File "/var/www/.venv/lib/python3.10/site-packages/channels/routing.py", line 116, in __call__
    raise ValueError("No route found for path %r." % path)
ValueError: No route found for path '/ws/progress/'.
2024-10-22 15:37:56,182 ERROR Exception inside application: No route found for path '/ws/logs/63d76550-96e4-4f77-83e0-6c3e4c352dba'.
Traceback (most recent call last):
  File "/var/www/.venv/lib/python3.10/site-packages/channels/routing.py", line 62, in __call__
    return await application(scope, receive, send)
  File "/var/www/.venv/lib/python3.10/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/var/www/.venv/lib/python3.10/site-packages/channels/sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/var/www/.venv/lib/python3.10/site-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "/var/www/.venv/lib/python3.10/site-packages/channels/middleware.py", line 24, in __call__
    return await self.inner(scope, receive, send)
  File "/var/www/.venv/lib/python3.10/site-packages/channels/routing.py", line 116, in __call__
    raise ValueError("No route found for path %r." % path)
ValueError: No route found for path '/ws/logs/63d76550-96e4-4f77-83e0-6c3e4c352dba'.
```

**Comment by BenediktMKuehne** [comment]
So far I haven't been able to reproduce the issue on my machines.

Can you give me more info?
 installation log / server logs

**Comment by secsonthebeach** [comment]
Hello. ‘Unable to reproduce’ makes me hopeful that it’s just something on my end. I have a network proxy to contend with too.  
Below are a couple of screenshots from relevant logs that I could find. I could not find an installation log. Do I need to run the installer again and tee it to a file?


- This one is from `/var/www/logs/daphne.log`
![var-www-logs-daphne-log](https://github.com/user-attachments/assets/51490d49-adc9-4738-84f5-4d4dae5b0f1a)

- This one is from `/var/www/embark/embark.log`
![var-www-embark-embark-log](https://github.com/user-attachments/assets/7c4a523c-2f52-4dd4-9273-5e68c0847edd)

**Comment by secsonthebeach** [comment]
Hello, I decided to uninstall and then reinstall. Everything seems to run smoothly, but I still encounter errors for the websockets. I exported the output for the install and run_server to rich text, but had to convert to pdf to upload. Please let me know what you think.

[embark-run-server-log.pdf](https://github.com/user-attachments/files/17760028/embark-run-server-log.pdf)
[embark-install-log.pdf](https://github.com/user-attachments/files/17760029/embark-install-log.pdf)

**Comment by BenediktMKuehne** [comment]
Those two logs look normal - no installation errors.
Maybe the pipenv installation failed somewhere the first time 🤔

Are there still routing errors with the websockets?

**Comment by secsonthebeach** [comment]
Yes, the re-install doesn’t seem to make any difference.
I’ll do some digging for Pipenv logs. 
Do you have a suggestion of where & what to look for?


Just poking around `/var/www/.venv` and it looks like things are installed, but I didn’t check line-by-line.

The overall web app works as expected. I am running a small firmware analysis now, just to have some data in there.

My particular setup does have some firewalling in front of it, which had me wondering if that could be the problem. So I have been testing on the local host with a tool called “websocat”.

From the same host, running `websocat ws://embark.local:8001/ws/progress/` returns a “500 Internal Server Error”, and I see the same stderr output from `run_server.sh` as I do when navigating to the “Progress” tab in a browser.

I get the same thing when using “localhost” instead of “embark.local”, and when trying the web socket client tool against the “/ws/logs/<hash>” URL path. 

I also just ran `pip list` from the activated Pipenv. All the default packages show as installed and the versions match the Pipfile.lock from the Embark repo.  I do not have the packages listed under ‘develop’ section of Pipfile.lock

**Comment by BenediktMKuehne** [comment]
We are seeing the same behavior on a fresh installation.
Will try and fix it in the next PR

**Comment by BenediktMKuehne** [comment]
my tests indicate some change within the daphne application
#222 should fix the issue
