### ISSUE TITLE
Main dashboard is empty

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#226]
**Describe the bug**
I ran a scan and I got the results and the report in Embark but the main dashboard remained blank.

**To Reproduce**
1. EMBArk installation in default mode
2. Start EMBArk: sudo ./run-server.sh -a <IP>
3. Use the firmware available here: https://github.com/jdpiercy/Kankun-SmartPlug/blob/master/Firmware%20-%20Stock/kkeps-3.1.bin
4. Do a scan
5. Check the dashboard

**Expected behavior**
Dashboard should show the Embark server's statistics.

**Screenshots**
![kép](https://github.com/user-attachments/assets/ea50b5cc-8e76-4c33-ab9c-6f29d802a058)

![kép](https://github.com/user-attachments/assets/dada032b-d95e-4a42-be13-47d478007e41)

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 22.04.5 LTS

**Comment by BenediktMKuehne** [comment]
Should there be something on the dashboard?
Are there results in the report?

EMBA might have not found anything.

**Comment by torabi12** [comment]
The report is fine and it contains a lot of findings:

![kép](https://github.com/user-attachments/assets/1900d718-223b-40da-a2f3-efea5689a446)

The details page is also OK:

![kép](https://github.com/user-attachments/assets/f27f3674-388f-49f2-a988-247920c4abb1)

**Comment by BenediktMKuehne** [comment]
You're right
Must be an importer bug than
Will take a look

**Comment by torabi12** [comment]
I did a brand new installation and tried another FW test which gave a good report:

![kép](https://github.com/user-attachments/assets/336f53c2-72ed-485d-b1e5-13fb852e7b98)

but the dashboard is empty for me. I believe this can be reproducible on other systems as well.

**Comment by BenediktMKuehne** [comment]
simple `git pull` should do the trick

**Comment by torabi12** [comment]
Thank you, the page is available again.
