### ISSUE TITLE
Kali Linux 2022.01 is out

### ISSUE THREAD

**Issue by m-1-k-3** [e-m-b-a/embark#32]
See here https://www.kali.org/blog/kali-linux-2022-1-release/

Need to wait till https://github.com/e-m-b-a/emba/issues/220 is finished

**Testcases:**

- [x] Installation
- [x] User add/remove/pw change/login
- [x] Login
- [x] EMBA test with default settings (check scan dashboard, main dashboard, EMBA report)
- [x] EMBA test with full scan settings (check scan dashboard, main dashboard, EMBA report)
- [x] Dashboard access without login
- [x] dev mode

**Comment by BenediktMKuehne** [comment]
VM with 4GB RAM doesn't seem to work anymore.    
prob due to Redis or cve_search updates.
8GB works fine
