### ISSUE TITLE
log path configuration in EMBArk

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#33]
Hi,
I would like to scan large bin files with EMBArk and the default 80GB disk space of kali is not enough to execute the test. First I just added a new partition but EMBArk was installed on the default /dev/sda1 partition and EMBArk does not support log parameter, it used the installation partition.
Now I have a separate /dev/sda3 and I installed EMBARk to this folder but in the future it would be great to install EMBArk to the default partition and if I would use the same -l option as EMBA offers I could put the logs and extracted items to a separate disk for huge binary scans.
If possible please look into the possibility of this.

**Comment by m-1-k-3** [comment]
We will not include the log path parameter in EMBArk. If you need more disk space you need to  mount a larger disk/partition to the EMBArk log directory. Do not forget to copy your current data to the new disk.
