### ISSUE TITLE
Scan progress frame height

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#34]
In EMBArk the scan progress pages shows the actual modules but the frame is very small, it would be better in bigger size:
![image](https://user-images.githubusercontent.com/98665813/157300692-de3800d2-7195-4ef2-851c-71e4cb69da53.png)

I know it is nice to have but it would be easier to follow and understand what is happening at the scan.

**Comment by keesj-exset** [comment]
Hi,
I am having a similar issue the page is even completely empty. the scan works (and I can see what is happening in the background) but it feels a bit empty.

![Screenshot from 2022-03-24 13-39-00](https://user-images.githubusercontent.com/62298192/159918069-2587ec5b-e40d-4885-8ca5-95be57567d64.png)
![Screenshot from 2022-03-24 13-38-32](https://user-images.githubusercontent.com/62298192/159918072-6fa81871-f14d-44c8-b82b-37bf498d2c9c.png)

**Comment by p4cx** [comment]
Hello, thank you for reporting these issues. The second one is already known to us and I will briefly explain it here for people who want to help improve EMBArk:
The status page is only updated when EMBA starts analyzing another module in the background. If you reload the page and EMBA has not yet started with a new module, you will not see the analysis status. There should be a reverse implementation: when the page loads, it should get the status from EMBA, regardless of whether EMBA started analyzing a new module (changed emba.log file if I'm not wrong) or not.

**Comment by torabi12** [comment]
Unfortunatelly I can not help you to improve the code, lack of developer knowledge :), but I think it would be enough just to make the white frame little bigger / higher, just to see the content and what is the real status of the actual activity. If it would be possible the present design would be much informative in my opinion to follow the scan.

**Comment by BenediktMKuehne** [comment]
Since #72 introduces some design changes, this issue is now outdated.

If there is still an interest in changing the size of the individual containers, grid-structure etc. please open a new issue
