### ISSUE TITLE
Minor findings in installation, startup and usage of EMBArk

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#51]
**Describe the bug**
During the installation the following errors came:

![kép](https://user-images.githubusercontent.com/98665813/184919625-d52a5d46-2737-40df-9279-3fa6379f87bd.png)

![kép](https://user-images.githubusercontent.com/98665813/184919661-2f08cad5-7b37-4e66-9721-0e76c63471a6.png)

![kép](https://user-images.githubusercontent.com/98665813/184919685-5e9c4941-50e0-4c08-a13e-47544f4e8759.png)

Starting EMBArk displays these issues:

![kép](https://user-images.githubusercontent.com/98665813/184919799-fca334a2-d17c-40bc-931b-d15e044969a2.png)

![kép](https://user-images.githubusercontent.com/98665813/184919814-fc0f502d-708d-4b16-a715-d722f3ce1687.png)

![kép](https://user-images.githubusercontent.com/98665813/184919854-0b9d4a8d-205a-4009-b08a-795180db4770.png)

Uploading a firmware file works fine but the path looks like this:

![kép](https://user-images.githubusercontent.com/98665813/184919989-29b9773c-2b90-41c1-88d1-da9a87748760.png)

The progress bar did not go to 100% but the san has been finished:

![kép](https://user-images.githubusercontent.com/98665813/184920131-3d645737-bd20-4682-a172-8a9b2bf95976.png)

I was able to reproduce this issue more times. I know the scan is finished when the fan slows down in the computer but the progress bar does not go to 100%.

I entered these parameters for the scan:
![kép](https://user-images.githubusercontent.com/98665813/184920396-aedf823b-c1bc-4e21-bd97-f47b35c1a198.png)

but the report contains these:
![kép](https://user-images.githubusercontent.com/98665813/184920451-ce6435c0-3a8c-448d-96c7-8f25614f66dc.png)

It would be very useful to show real version numbers and proper data in the report, because if I have more scans difficult to check the real versions if the data is incomplete.

**To Reproduce**
1. EMBArk installation (default mode)
2. Start EMBArk: sudo ./run-server.sh
3. Use the firmware available here:
https://cyberforat.squat.net/openwrt/binary_images/linksys_official/WRT54GS_3.17.4_US_code.zip
5. See error

**Expected behavior**
Please fix the errors if posible.

**Screenshots**
Attached above.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS Desktop

**Comment by torabi12** [comment]
I checked the same on Kali 2022.3.

During the EMBArk installation there were these warnings:
![kép](https://user-images.githubusercontent.com/98665813/185743452-5aa9d0eb-4ca3-4ee0-a754-7ff13f26d27a.png)

![kép](https://user-images.githubusercontent.com/98665813/185743457-3d4c4f82-b984-462e-8c16-4b44594585b4.png)

I use a brand new workstation with 11th gen i7 CPU with latest BIOS but I got this more times:
![kép](https://user-images.githubusercontent.com/98665813/185743475-cc2e330c-d1c3-443c-8f53-f75e8dde19c1.png)

and the final one:
![kép](https://user-images.githubusercontent.com/98665813/185743479-ba68d041-7c25-4725-b7fb-c528bef6033b.png)

Usage of EMBArk:
Same fakepath as on Ubuntu and on Kali:
![kép](https://user-images.githubusercontent.com/98665813/185743493-51720349-fe3c-4484-b128-00956422c751.png)

The progress bar also stopped again but the scan has been finished for sure:
![kép](https://user-images.githubusercontent.com/98665813/185743499-d88812c4-4f0e-4e00-91aa-ba85f1cdcb6c.png)

and the final report is incomplete:
![kép](https://user-images.githubusercontent.com/98665813/185743509-b3483a5b-5bfe-4eb6-bec0-1903db754e6f.png)

OS: Kali 2022.3
VMware Workstation Pro 16

**Comment by BenediktMKuehne** [comment]
Hi torabi,

the uploader and the reporter problem are there for anti code-injection stuff.
They will eventually be back to working as expected.

The progress-bar overhaul is on the TODO-list. It has some design flaws at the moment.

the warnings etc in #53

**Comment by BenediktMKuehne** [comment]
pipenv warnings are related to this https://github.com/pypa/pipenv/issues/5208

**Comment by m-1-k-3** [comment]
> pipenv warnings are related to this [pypa/pipenv#5208](https://github.com/pypa/pipenv/issues/5208)

Thank you for the resource. We have such warnings in multiple areas in EMBA.

**Comment by torabi12** [comment]
Hello Benedikt,

I checked today the upload and reporting in EMBArk and I have these info:

![kép](https://user-images.githubusercontent.com/98665813/187487912-e2e9a1a9-2a72-4fe9-b542-ef01863d849d.png)

I added these parameters:
![kép](https://user-images.githubusercontent.com/98665813/187487965-ec71733a-7842-443a-b41e-97c6b7824212.png)

and I got this back:
![kép](https://user-images.githubusercontent.com/98665813/187487999-6843ede7-2bcf-46fc-ab3f-5ef88dd07c6c.png)

The final report would be important I think because the user would store only the html pages of the scans.
Could you check it on your side please? Thank you.

**Comment by m-1-k-3** [comment]
@torabi12 please open a new ticket for better tracking

Thank you
