### ISSUE TITLE
Final report header fix

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#56]
Hello Benedikt,

I checked today the upload and reporting in EMBArk and I have these info:

![kép](https://user-images.githubusercontent.com/98665813/187491912-a041f35a-de73-408e-a349-2a9ae737cbf2.png)

I added these parameters:
![kép](https://user-images.githubusercontent.com/98665813/187491938-65a00c9c-3027-46f7-88ef-7479a8911e4e.png)

and I got this back:
![kép](https://user-images.githubusercontent.com/98665813/187491962-d71c92c1-63cd-4cf7-9530-8b2d81661eb3.png)

The final report would be important I think because the user would store only the html pages of the scans.
Could you check it on your side please? Thank you.

**To Reproduce**
1. EMBArk installation (default mode)
2. Start EMBArk: sudo ./run-server.sh
3. Use any firmware
4. See the issues.

**Expected behavior**
Final HTML report should contain the same version number and notes of the actual scan.

**Desktop (please complete the following information):**
 - OS: [Kali Linux 2022.3]

**Comment by BenediktMKuehne** [comment]
Will address this in #54

**Comment by torabi12** [comment]
I checked again the path in the file upload and the final report in EMBArk,

The path is still strange on Kali linux:
![kép](https://user-images.githubusercontent.com/98665813/187898107-47308674-f9e5-4c59-a164-ccd5e72f37d3.png)

These were my notes before the scan:
![kép](https://user-images.githubusercontent.com/98665813/187898155-b3094383-03cb-4c2b-a728-7e87973a47e0.png)

I got these in the report:
![kép](https://user-images.githubusercontent.com/98665813/187898188-02337d48-35c2-47a1-9b0e-27bc6ceafdb6.png)

Version number filed works fine, but I think the device line looses the space characters and the notes field looses " on Kali".

I got this with a new installation a few minutes before.
