### ISSUE TITLE
EMBArk fast test

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#60]
Hello Benedikt,

I have seen the new release today and I installed a new Kali 2022.3 VM afternon with the actual EMBArk.
Installation was fine I think.

Starting the server dropped and error but the service was reachable after this:
![kép](https://user-images.githubusercontent.com/98665813/197016105-5e9695c0-1ed3-4d2a-8552-ab67af53465f.png)

I did a short scan but the progress bar stopped at 91%:
![kép](https://user-images.githubusercontent.com/98665813/197016192-5ff8f80f-0c4f-4dff-b00a-1f024511ae70.png)

The scan was over for sure.

After this I checked the details of the scan and the page only displayed the enthropy graph:
![kép](https://user-images.githubusercontent.com/98665813/197016344-04954d54-3856-45bf-94f5-476f51fb4323.png)

I though it was because of the wrong FW file and I wanted to start the 2nd scan but I got an error after I wanted to start the scan:
![kép](https://user-images.githubusercontent.com/98665813/197016516-b5d9c84a-68cd-4d8a-b579-37061a2f2cd0.png)

I logged out and stopped EMBArk and started again. I got the first No such service: EMBA error like on the first screenshot and I couldn't start a new scan because the last error came up again.

*************

I tried again the same with a brand new installation.
A stating error in the terminal came again. I was able to start the 2nd scan. Please ignore the empty page issue of the details page, because another FW scan displayed the contents fine.
I am not sure the progress bar works perfect or not but I am going to try and check it some more times. Maybe the fix is still in progress for this.

I also checked the firmware delete page and it was blank:
![kép](https://user-images.githubusercontent.com/98665813/197049022-5785f6fb-b5bc-43f0-9bd0-bf02abeb36c3.png)

Thank you!
torabi

**Comment by BenediktMKuehne** [comment]
Will be looking into this momentarily.
The progress bar issue: e-m-b-a/embark#59

**Comment by BenediktMKuehne** [comment]
@torabi12 all these bugs should be fixed now. Except this one (still looking into this):

> Starting the server dropped and error but the service was reachable after this: ![kép](https://user-images.githubusercontent.com/98665813/197016105-5e9695c0-1ed3-4d2a-8552-ab67af53465f.png)

**Comment by torabi12** [comment]
Hello Benedikt,

I did some tests today on EMBArk.

- The issue with the progress bar looks disappeared, at the end of the scans the progress bar just gone, and in the Analysis menu the actual task also disappeared. The problem is that the Report page did not show any results after the scan. I did 2 analysis' and it is still empty now:
![kép](https://user-images.githubusercontent.com/98665813/198362287-5d950796-c70f-464d-868a-ffeb04f2cb54.png)

In the filesystem the folders are available:
![kép](https://user-images.githubusercontent.com/98665813/198362489-7523e85c-a36c-4dde-84c3-9014e272c6a3.png)

- I checked the delete function and it was working. I don't know the path in the filesystem of the firmwares, but the page works fine.
- At the file upload the function works good but I miss the confirmation window that the upload was successful. As I remember it used to display it.
I can create a vendor name, I think I understand this field, but the label name is not clear for me. Does the label belong to "routers" or "Iot stuff" or something similar? There is also a device name field and I can assign the label and vendor values for that. But how can I delete a label or a vendor if I don't need any of them? I deleted all the uploaded FW files, but these names remain on the list. It is not a problem maybe, but I can't see the structure behind the windows. My personal opinion is that this part is a bit too complicated. Maybe just for me :)

- I checked the  final report and it is also much better:
![kép](https://user-images.githubusercontent.com/98665813/198364853-d7287ffc-1fb0-4698-814e-281299d5b749.png)

The small problems are that the Firmware Vendor contains "Vendor" also but I didn't enter this on the page.
The version looks perfect.
In the notes field the string is fine, but I added the full file name like: WRT54GS_3.17.4_US_code.bin

and the dot was gone.
It is strange that the final report is very complex and I didn't find any problem somewhere else, only the very basic info fields were problematic.
Hope the results will help you in the future if any of them is valid.

Regards,
torabi

**Comment by BenediktMKuehne** [comment]
e-m-b-a/emba#372

**Comment by torabi12** [comment]
I tried again EMBArk and after a scan the detailed view was working fine.
I went to other pages, I deleted the FW file and after that I went back to the reports page. The scan was there but the Detailed View dropped an incomplete page:
![kép](https://user-images.githubusercontent.com/98665813/198714768-400982ea-401d-4f3d-babc-8583d7c17a7a.png)

The Main page shows the scan correctly:
![kép](https://user-images.githubusercontent.com/98665813/198714857-3bad5684-e0fc-4b26-bcad-473411514f1a.png)

The final report is like this:
![kép](https://user-images.githubusercontent.com/98665813/198715053-1e61c7d6-0781-409e-b472-b892dc01e0d6.png)

I found the upload successful message:
![kép](https://user-images.githubusercontent.com/98665813/198715229-30cdf824-0162-425a-bc33-7f91ab77d4f3.png)

Maybe I missed it yesterday.

**Comment by torabi12** [comment]
I checked again the latest emba/EMBArk today. The "Detail View" was working after the scan but I deleted the firmware file and this page became blank except the enthropy graph:
![kép](https://user-images.githubusercontent.com/98665813/198985100-43d3b3da-b7f1-476c-b50f-1ce2f6f8674c.png)

Would it be possible to display the detailed view page for the previus scans even if the were deleted?

**Comment by BenediktMKuehne** [comment]
I think this is just a bug in the view function.
Will take a look.
Ty

**Comment by torabi12** [comment]
I checked again today. After the scan report is available:
![kép](https://user-images.githubusercontent.com/98665813/199555766-5c7dd9c1-88c3-487e-a502-eb1d1e43cc12.png)

The Download Logs does not work:
![kép](https://user-images.githubusercontent.com/98665813/199555832-d0a3817c-4f2a-4f67-8422-855e66e9ddec.png)

Open report and Detailed views are fine.

After this I deleted the FW file and checked the same. Download dropped the same error like above, and the open report and the detailed view were correct:
![kép](https://user-images.githubusercontent.com/98665813/199556146-4809fcc7-ac22-4ff3-8f4d-04221a5a7fb5.png)

Could you please verify the download?

**Comment by torabi12** [comment]
I checked again the report download (Download Logs) on a brand new installation but it didn't work. Error is the same:
"Error occured while querying for Firmware object"

**Comment by BenediktMKuehne** [comment]
That's definitely a bug, happens when the zipping of the log folder fails.
The response message is rather misleading :D
Will fix.

**Comment by torabi12** [comment]
This would be an important feature to download the logs.
Thanks.

**Comment by BenediktMKuehne** [comment]
#68, but testing will take some time.

**Comment by torabi12** [comment]
May I participate in the testing?
Please let me know how to download if it is available.

**Comment by torabi12** [comment]
I executed some tests today but I did not get the results in EMBArk. The report page remained empty after the first scan, and now the 2nd one just hangs at 75% and nothing happens.

I stopped it manually and I got this:
![kép](https://user-images.githubusercontent.com/98665813/201421342-b5b72064-9729-4aea-9e1a-5eb24310f4c2.png)

I use Kali 2022.3.

**Comment by BenediktMKuehne** [comment]
> I executed some tests today but I did not get the results in EMBArk. The report page remained empty after the first scan, and now the 2nd one just hangs at 75% and nothing happens.
> 
> I stopped it manually and I got this: ![kép](https://user-images.githubusercontent.com/98665813/201421342-b5b72064-9729-4aea-9e1a-5eb24310f4c2.png)
> 
> I use Kali 2022.3.

With #72 this issue should also disappear since there now is better/more status-information for each analysis.
Even `pkill -f emba.sh` shouldn't lead to backend inconsistencies.

**Comment by torabi12** [comment]
For me the first scan hangs in the browser at his point:
![kép](https://user-images.githubusercontent.com/98665813/205063967-95186ee8-dd8c-40fb-a015-dc3991fd221f.png)

and if I stop it:
![kép](https://user-images.githubusercontent.com/98665813/205064056-7910ad4b-a29a-4fea-8bc3-af2045c10594.png)

but I make another new VM and try again...

**Comment by torabi12** [comment]
Hello Benedikt,

I tried 2 times today the scan in EMBArk with the same BIN file. Both stopped around 49%.

![kép](https://user-images.githubusercontent.com/98665813/205146908-0095244c-dafc-49a7-9057-edd55f4bcf28.png)

After manual stop I got this:
![kép](https://user-images.githubusercontent.com/98665813/205146946-8d2e2fb2-0d16-4ee8-97b6-e205edb13263.png)

I checked the logs in the file system and there is the first folder:
![kép](https://user-images.githubusercontent.com/98665813/205147052-d62a0233-e7d7-4e5c-ac0d-c45e709a98b2.png)

CPU usage dropped to 0% and nothing happened.

Could you please try a default scan in EMBArk for
https://download.zyxel.com/GS1200-5/firmware/GS1200-5_V2.00(ABKM.2)C0.zip

I extracted the ZIP and I only uploaded the BIN file for the scan. I just selected the CVE-search befor starting it.
I use the latest Kali fully updated with apt.

When I gave up and hit CTRL+C to stop EMBArk I got this in the terminal:
![kép](https://user-images.githubusercontent.com/98665813/205148341-175d8eb3-a918-44d4-93d0-7c200b8f9569.png)

Maybe it is some temporary error with this specific binary.

**Comment by m-1-k-3** [comment]
I'm currently running some EMBA tests on this firmware. I have identified some little issues that I will fix today. Currently I don't know if this affects the EMBArk run. We need to check this afterwards with the EMBA fixes in place.

**Comment by BenediktMKuehne** [comment]
> When I gave up and hit CTRL+C to stop EMBArk I got this in the terminal:
> ![kép](https://user-images.githubusercontent.com/98665813/205148341-175d8eb3-a918-44d4-93d0-7c200b8f9569.png)

That's a known problem with the new shutdown-handler, but it has minimal to no impact. (except the output of course)

**Comment by torabi12** [comment]
> I'm currently running some EMBA tests on this firmware. I have identified some little issues that I will fix today. Currently I don't know if this affects the EMBArk run. We need to check this afterwards with the EMBA fixes in place.

Thank you, I am going to do an EMBA scan after the update. Likely tonight...

**Comment by torabi12** [comment]
> > When I gave up and hit CTRL+C to stop EMBArk I got this in the terminal:
> 
> That's a known problem with the new shutdown-handler, but it has minimal to no impact. (except the output of course)

Thank you, I didn't know, just wanted to share all the things from my side.

**Comment by m-1-k-3** [comment]
> > I'm currently running some EMBA tests on this firmware. I have identified some little issues that I will fix today. Currently I don't know if this affects the EMBArk run. We need to check this afterwards with the EMBA fixes in place.
> 
> Thank you, I am going to do an EMBA scan after the update. Likely tonight...

argl was running out of disk space after 22gig

**Comment by m-1-k-3** [comment]
The EMBA updates are merged and can be tested.
**Important: We also changed the docker image which requires updating the docker image.**

**Comment by torabi12** [comment]
I started the scan this morning and it is still running. Looks fine everything but I don't know how long does it take....
I thought this small switch firmware is a good test file:)
![kép](https://user-images.githubusercontent.com/98665813/205449085-378658f5-bba4-4adf-8d4c-8327868f91fb.png)

**Comment by m-1-k-3** [comment]
Looks as it is not a good testfile to see nice EMBA results ;) As EMBA was not able to identify a Linux system it extracted a lot of "junk" files via multiple extraction rounds. The deep extractor has not found a linux system and created a huge amount of these files which are now analysed. 
Do you have more details about this firmware? Is it a Linux? Which filesytem? Is there a documented way to extract the firmware?

**Comment by torabi12** [comment]
I have no info about the file, I just wanted to scan my home switch's latest firmware file.

![kép](https://user-images.githubusercontent.com/98665813/205450109-a56b7df6-80a6-4bdd-99b2-66c7dfec3536.png)

Before starting the scan I increased the Kali's default 80 GB filesystem to 200GB. I hope it will be enough to finish this.

**Comment by torabi12** [comment]
Finally I have the result:
![kép](https://user-images.githubusercontent.com/98665813/205461358-9aad55c1-55bc-458c-a84b-eee8bb641c4c.png)

Tomorrow I will do another EMBArk scan with a better firmware file, to close this ticket.

**Comment by torabi12** [comment]
Hello Benedikt,

I did an EMBArk scan today and worked fine.
- Progress bar went fully up and after the scan it displayed a message:
![kép](https://user-images.githubusercontent.com/98665813/205490245-54b26b4a-1b49-410e-a079-169b48264009.png)

- Report can be downloaded and viewed:
![kép](https://user-images.githubusercontent.com/98665813/205490267-01a96d15-45e5-4cc6-87e7-0d3efd1c9f64.png)

![kép](https://user-images.githubusercontent.com/98665813/205490316-428230c8-e405-4012-a743-c209ebbd3678.png)

- Details page was also working

- Firmware delete was OK, and after deletion the report and info were available inside EMBArk.
- The Main page was also fine, I only missed the entropie graph, but I did only one scan I don't know what should be the content:
![kép](https://user-images.githubusercontent.com/98665813/205490364-5266d69f-e8fd-440c-9281-1cca9376be86.png)

- After stopping the service the terminal content were nice:
![kép](https://user-images.githubusercontent.com/98665813/205490421-cb605564-3049-48d8-b6bb-40846de71746.png)

Thank you all the fixes, I think this ticket can be closed.
-

**Comment by BenediktMKuehne** [comment]
> ![kép](https://user-images.githubusercontent.com/98665813/205490316-428230c8-e405-4012-a743-c209ebbd3678.png)
> 
> * Details page was also working
> * Firmware delete was OK, and after deletion the report and info were available inside EMBArk.
> * The Main page was also fine, I only missed the entropie graph, but I did only one scan I don't know what should be the content:
>   ![kép](https://user-images.githubusercontent.com/98665813/205490364-5266d69f-e8fd-440c-9281-1cca9376be86.png)

Since the entropy value is 0 the graph looks as expected.
The weird thing is, this would mean there is no information in the data...
I'll add that to my TODO-list 👍
