### ISSUE TITLE
Toggle Tests for each scan

### ISSUE THREAD

**Issue by jblu42** [e-m-b-a/embark#62]
Hi

Thanks for your great work on embark! Came across this some time and follow your development. While working with Emba I come across several things that would be great to be implemented, I will add them as feature requests for the projects, so it can be discussed if they are valid or not.

Feature request:
It would be great to have the possibility to disable individual tests. 

For example the grepit tests takes a lot of time but delivers only marginal results. It would be great to customize the scan as much as possible. 

There is already an "Expert Mode" when starting the scan, so it would be good if all modules / scans could be toggled on / off here.

I think in uploader/tests.py or uploader/models.py the command line options for emba are defined, have not looked into detail if this can be modified there.

**Comment by m-1-k-3** [comment]
Hi @jblu42, we have this feature already in EMBA and planned it for EMBArk.

**Comment by m-1-k-3** [comment]
addressed in https://github.com/e-m-b-a/embark/pull/83
