### ISSUE TITLE
"Firmware scan status" view missing

### ISSUE THREAD

**Issue by senthilkumarmoorthy** [e-m-b-a/embark#73]
**Describe the bug**
Couldn't find "Firmware scan status" view in the dashboard

**To Reproduce**
1. EMBArk installation (default mode)
2. Start EMBArk: sudo ./run-server.sh -a 192.168.1.20

**Expected behavior**
1. Once after the firmware uploaded and option selected to analyze, I could find the option to view the scan status.

**Screenshots**
![image](https://user-images.githubusercontent.com/34002534/204903468-909f1959-a332-4c59-b811-a62e6b6ee5b6.png)

**Desktop (please complete the following information):**
 - OS: Kali Linux 2022.03

**Additional context**
1. Upon selecting the option "Progress" in the right-side panel I could only see the option "Select and stop Analysis" but I couldn't get an option anywhere in the dashboard as mentioned in the image located https://github.com/e-m-b-a/embark/wiki/Web-interface#firmware-scan-status
2. All I could do is that I can choose the firmware which I uploaded in the drop-down under "Select and stop Analysis" and a STOP button.
Am I missing something during the installation, or any configuration needs to be changed to view the scan status? Please advise.

**Comment by BenediktMKuehne** [comment]
I'm not 100% certain i understand the steps you took.

1. First you uploaded the firmware here:
![image](https://user-images.githubusercontent.com/62940240/204985524-fc1add93-e52e-4444-8db0-04db837df0c7.png)

2. Then you started the analysis here:
![image](https://user-images.githubusercontent.com/62940240/204985937-a901b22c-cf88-4caa-8b68-ec88bae3d935.png)

3. You got redirected to the service-dashboard
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/34002534/204903468-909f1959-a332-4c59-b811-a62e6b6ee5b6.png)

Did the scan complete and you're just looking for the reports (results)?
--> clipboard icon on the nav-bar directs to the reports


Or did you have a problem with the service-dashboard and the issue is about not getting status information?
(normal operation looks like this 
![image](https://user-images.githubusercontent.com/62940240/204987951-5aa488a9-96e5-45f8-a365-78db1b7ba1fd.png)
)

**Comment by senthilkumarmoorthy** [comment]
All points which you mentioned here is exactly I follow to get the scan file uploaded and to get it scanned and to view the report, but all I need is the status of the scan progress as mentioned in the documentation. Screenshot taken from the documentation shown below.

![image](https://user-images.githubusercontent.com/34002534/204997494-6caa69f2-ba4f-41d4-a64f-c05b7df9f8e4.jpeg)

As I said I can get the report after the scan gets completed but I don't see an option like shown in the above image to get to know on what is the current status of the scan until I see a report file generated.

**Comment by BenediktMKuehne** [comment]
👍 
If updating is possible, the newest version might potentially fix your issue.

Should the problem persist or you can't upgrade, the first thing i would need are the logs.
particularly the `/var/www/embark/embark.log`.
Try refreshing the page and look at the last 50-ish lines.
A trace of the network connection for `/progress` might be helpful as well.(CRTL+shift+i in chrome)

**Comment by senthilkumarmoorthy** [comment]
Im happy that you got my issue now. So, this issue which I been facing been there since I started using EMBARK 5 months back itself. In this 5 months I have done fresh installation at least 5+ times in many host either in Virtualization and in Bare metal but this issue which I was facing been there in all the installation I had, which means I'm making some mistake. I always wonder how others are getting and why am I not getting a luck to have it. All my installations are in kali so I'm not sure is it bcoz of some pkg in kali which isn't letting me I don't know. May I also ask by selecting which option in the sidebar usually let us to view the progress bar of scan.?

**Comment by senthilkumarmoorthy** [comment]
Like you advised, I'm going to do it again one more time 😁 with a fresh VM and fresh EMBARK deployment. I will come back to you shortly once that's done.

**Comment by BenediktMKuehne** [comment]
> May I also ask by selecting which option in the sidebar usually let us to view the progress bar of scan.?

The Service-dashboard is currently represented by the Clock-icon
