### ISSUE TITLE
Entropy value is always zero in detailed view

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#75]
**Describe the bug**
The final report contains enthropy graph and value but the detailed view in EMBArk shows only 0.
![kép](https://user-images.githubusercontent.com/98665813/205720389-d2d4ca24-306e-4c96-98e6-94f348b2396a.png)

![kép](https://user-images.githubusercontent.com/98665813/205720409-f2afeac9-d380-46c7-936b-a43a1ca256f2.png)

![kép](https://user-images.githubusercontent.com/98665813/205720429-242e7692-5017-45d9-baf1-77139c491613.png)

so the graph on the main page is missing:

![kép](https://user-images.githubusercontent.com/98665813/205720536-2321acf7-2fca-4cab-b341-c950cb170a1b.png)

**To Reproduce**
1. EMBArk installation (default mode)
2. Start EMBArk: sudo ./run-server.sh
3. Use the firmware available here: anything
4. Do a scan
5. Check enthropy on detailed view page.

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 22.04.1

**Comment by m-1-k-3** [comment]
btw ... we will remove the Entropy statistics from the dashboard in the near future.
