### ISSUE TITLE
Some incompatible package on Kali linux 2022.4

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#76]
**Describe the bug**
I would like to ask if the following message causes a problem during installation?

![kép](https://user-images.githubusercontent.com/98665813/206292151-fe67c424-029f-419d-b4cc-21bec271bf24.png)

The same error came 2 times during the installation of EMBArk.

**To Reproduce**
1. EMBArk installation (default mode)
2. Check the instalattion logs

**Desktop (please complete the following information):**
 - OS: Kali Linux 2022.4 - VMWare Workstation Pro

**Comment by m-1-k-3** [comment]
EMBArk does not support Kali as host system anymore. See here https://github.com/e-m-b-a/embark/wiki/Installation#prerequisites

**Comment by torabi12** [comment]
Then my question is not relevant. Thank you.

**Comment by m-1-k-3** [comment]
As I'm currently testing EMBA on the fresh Kali 2022.4 I have realized that this is not an EMBArk issue. It is from EMBA and so I will move it to EMBA.
