### ISSUE TITLE
Installation logfile and OVF export questions

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#77]
**Describe the bug**
Hello Benedikt,

1st question:
Could you please help me where I can find the log file of EMBArk installation on Ubuntu server?

2nd question:
I installed EMBArk on Ubuntu Server 22.04.1 and works fine but I exported the system to an OVF file and I imported in ESXi 8.0. The scan is working also and I get sucsess message on ESXi but there is no report and download log for the scan.
Could you help which log would be valuable for this problem?

**To Reproduce**
1. EMBArk installation (default mode)
2. Start EMBArk: sudo ./run-server.sh -a <IP of the ubuntu server>
3. Use the firmware available here: Sorry don't remember but the scan was OK.
4. After the scan there is no report in EMBArk in case of host ESXi 8.0 environment.

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 22.04.1

**Comment by BenediktMKuehne** [comment]
> 1st question:
> Could you please help me where I can find the log file of EMBArk installation on Ubuntu server?

There is no log-file for the installation, you would have to do that manually

Regarding the rest, the default log is under /var/www/embark/embark.log

The service-dashboard might show the analysis as successful even if it failed, its just an indicator that it completed.
If it does not pop up on the report-dashboard it probably failed.
I'm working on displaying even failed analysis.

Best way to find out why it failed without running it in EMBA directly, would be to search the logs under /var/www/emba_logs/<the_uid_of_the_analysis>/

**Comment by torabi12** [comment]
This week I tried again the export from Workstation to ESXi and it is working.
Thank you the log's path.

As far as I know the terminal scroll does not work on ubuntu server by default and without install log output difficult to follow and verify the events during the installation of EMBArk.
