### ISSUE TITLE
CVE db issue on Ubuntu Server

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#80]
**Describe the bug**
I installed EMBArk in docker mode and I did not find the CVE download section at the end of the installation. The installation output was redirected into a file, which is uploaded to this report. When I started the EMBArk server I got some errors about cve-search is not OK.

**To Reproduce**
1. EMBArk installation (docker-mode)
2. Start EMBArk: sudo ./run-server.sh
3. See error

**Expected behavior**
I know the issue 187 workarounds but I tried 3 times the instalation on a clean Ubuntu Server and I got the same errors all the time.
I would like help to get the installer to handle the database download.

**Screenshots**
![kép](https://user-images.githubusercontent.com/98665813/210178947-ee5782a9-5d7b-4b62-b899-3000c24c29b5.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 22.04.1

**Additional context**
Full installation log
[install.txt](https://github.com/e-m-b-a/embark/files/10329125/install.txt)

**Comment by m-1-k-3** [comment]
Indeed ... something is going wrong. The cve-search installation is done by EMBA. 
Have you tried to start all the services manually (mongod and redis-server) and update the CVE search database with the `external/cve-search/sbin/db_updater.py` script?

**Comment by torabi12** [comment]
I didn't try the manual fix, I am going to do it tonight.
I did an EMBA install on the latest Kali yesterday and it was working fine. This issue came only on Ubuntu Server with EMBArk installation.

**Comment by torabi12** [comment]
I started mongod and redis but the update was not working:
![kép](https://user-images.githubusercontent.com/98665813/210241872-2fa399a7-82f0-4a90-bb07-df189cc32711.png)

**Comment by m-1-k-3** [comment]
could you try to install the `werkzeug` package:

```
pip3 install werkzeug
```

**Comment by torabi12** [comment]
After `werkzeug` package I got shorter error:

![kép](https://user-images.githubusercontent.com/98665813/210245316-46f35612-ee4e-4d4d-b98f-673072d8b59a.png)

**Comment by m-1-k-3** [comment]
looks like we are missing some dependencies:

```
pip3 install python-dateutil
```

**Comment by torabi12** [comment]
Thank you, now it is processing the DB:

![kép](https://user-images.githubusercontent.com/98665813/210252573-88097c08-b5fa-48d6-ac94-bd91aa887ef6.png)

**Comment by m-1-k-3** [comment]
Perfect :)
I will update the dependencies in the EMBA installer.

Thank you for your ongoing testing and reporting effort!
