### ISSUE TITLE
emba_updater without branch - question

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#82]
**Describe the bug**
I checked the emba_updater script on Kali (using emba) and on Ubuntu Server (using EMBArk) and on Kali the main repository is used:
![image](https://user-images.githubusercontent.com/98665813/219582308-4d5407ac-0c0a-4f82-a000-838d7aecb4e5.png)

but on Ubuntu Server I have to define the branch manually:
![image](https://user-images.githubusercontent.com/98665813/219582402-f74b771d-f675-411e-ba13-3fce61b6262d.png)

**To Reproduce**
1. EMBArk installation (default mode)
2. Start EMBArk update script: sudo ./emba_updater
3. See git messages.

**Expected behavior**
EMBArk update script should work without manual hit configuration.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Kali Linux 2022.4 and Ubuntu Server 22.04.1

**Comment by m-1-k-3** [comment]
Could you try changing the following line:

```
git pull | tee -a "$LOG_DIR"/emba_update.log
```
to 
```
git pull origin master | tee -a "$LOG_DIR"/emba_update.log
```

**Comment by torabi12** [comment]
After the modification it was working on Ubuntu Server:
![kép](https://user-images.githubusercontent.com/98665813/219876586-1fc5332b-8ef2-494f-acfe-f0e5fa5a58fd.png)

Thank you!
