### ISSUE TITLE
Name conventions

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#87]
**Describe the bug**
I created a "D-Link" vendor in EMBArk but the test did not start, because the name contains hyphen, which is blocked by EMBA.
I tried to start the same test without selecting the existing vendor but the test also did not start. I created again a new scan with DLink vendor and it worked fine:

![kép](https://user-images.githubusercontent.com/98665813/221355451-bc3b0556-ecdd-4594-93b6-3b045214d441.png)

**To Reproduce**
1. EMBArk installation default-mode
2. Start EMBArk: sudo ./run-server.sh -a <IP>
3. Use the firmware available here: anything
4. Create a vendor or device with a non supported character and assign it to the FW file and try to start the scan.
5. There is no error, the test stops after a few seconds.

**Expected behavior**
EMBArk should warn the user and only the supported characters would be accepted on the page.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 22.04.1

**Comment by m-1-k-3** [comment]
we need to adjust these filters. As quick fix I have included further allowed characters (-_) in EMBA.
