### ISSUE TITLE
Analysis failed in EMBArk only on dashboard

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#92]
**Describe the bug**
I executed an EMBArk and an emba scan for the same kkeps.bin file.
The problem is that the analysis failed in EMBArk.
![kép](https://user-images.githubusercontent.com/98665813/222738549-f7bd641d-3b9d-4dc2-94b9-d4aba5459e10.png)

I used the:
$ sudo ./emba -l ~/Kankun -f ~/kkeps.bin -p ./scan-profiles/default-scan.emba -X 1.0 -Y Kankun -Z Smartplug -N kkeps

command and it was fine, I got the report at the end.

In EMBArk the report also available, but I can get it from the file system only, and the Dashboard does not show any test results and the report page does not allow downloading the outcome.

Please see the logs from emba and from EMBArk below.

**To Reproduce**
Run a cwe scan for kkeps.bin in EMBArk.

1. EMBArk installation default mode
2. Start EMBArk: sudo ./run-server.sh -a 192.168.0.X
3. Use the firmware available here: <Insert URL> see below.
4. Analysis Failed.

**Expected behavior**
EMBArk should allow to download the created logs.

**Screenshots**
Like above.

**Desktop (please complete the following information):**
 - OS: Kali Linux 2022.4 for emba and Ubuntu Server 22.04.1 for EMBArk

**Additional context**
Logs from emba:
[emba.log](https://github.com/e-m-b-a/embark/files/10882600/emba.log)

Logs from EMBArk:
[emba_run.log](https://github.com/e-m-b-a/embark/files/10882605/emba_run.log)

FW file:
[kkeps.zip](https://github.com/e-m-b-a/embark/files/10882691/kkeps.zip)

**Comment by torabi12** [comment]
I checked the compare with another openwrt firmware and the emba scan was ok with default-scan profile, but in EMBArk the analysis failed.
I used this file for testing:

https://downloads.openwrt.org/releases/18.06.0/targets/ar71xx/generic/openwrt-18.06.0-ar71xx-generic-wrt160nl-squashfs-factory.bin

I got failed in EMBArk:
![kép](https://user-images.githubusercontent.com/98665813/223453600-e6ecbf8e-a46e-4621-8a1b-3770f1f65b86.png)

and the Ubuntu's console displayed some errors during the scan:
![kép](https://user-images.githubusercontent.com/98665813/223453769-6ec06ea7-16e2-4a3b-8997-ce25349c82e3.png)

**Comment by BenediktMKuehne** [comment]
Looking into it

**Comment by m-1-k-3** [comment]
The shown errors could be from s115 emulation module.

**Comment by BenediktMKuehne** [comment]
![image](https://user-images.githubusercontent.com/62940240/223679929-e0309039-a7ef-4420-bc38-d4a3e1a61286.png)

analysis works correctly, the problem seems to be in the post-processing

**Comment by m-1-k-3** [comment]
Should be solved by #93

**Comment by torabi12** [comment]
I checked again the above FWs and both were OK in EMBArk. Thank you!!

I wanted to scan an HP Docking Station's binary and I got a similar issue, according the logs all the things are fine but EMBArk displays a failure at the end like above.

FW file:
https://ftp.hp.com/pub/softpaq/sp100001-100500/sp100099.exe

I extracted it and I used the tesla_firmware_hp_Ver2_33_004.eeprom inside.

The logs from EMBArk:
[HP-UltraSlim_EMBArk-logs.zip](https://github.com/e-m-b-a/embark/files/10946010/HP-UltraSlim_EMBArk-logs.zip)

Maybe it is not the best FW for scanning but it would be great to have the logs and to display the statistics on the dashboard which are missing now.

* * * * * * * * * * * * * * *
I would give a last example, maybe it helps. I wanted to scan an UEFI Bios for Dell PowerEdge server. The initial release from 2017 is here:
https://dl.dell.com/FOLDER04612973M/1/BIOS_DT5JM_WN64_1.2.11.EXE

I grabbed out the cap file and the scan was long, at least 5 hours in emba.

FwHunt had some fwhunt_scan_analyzer.py errors during the scan, but the report generated.
Logs from EMBArk:
[emba_run.log](https://github.com/e-m-b-a/embark/files/10948993/emba_run.log)
[logreader.log](https://github.com/e-m-b-a/embark/files/10948994/logreader.log)

at the end I got failure on the page:
![kép](https://user-images.githubusercontent.com/98665813/224498754-4f63d700-3de4-4118-83ff-e47ca4b2329d.png)

**Comment by torabi12** [comment]
It is a mixed story but I found a similar test which was unfinished after 11 hours running. I wanted to scan an Asus motherboard's BIOS from here:
https://dlcdnets.asus.com/pub/ASUS/mb/LGA1151/H110M-A/H110M-A-ASUS-3805.zip
I used the CAP file inside: H110M-A-ASUS-3805.CAP
with Expert Mode, selecting all the categories on the page.

I followed the modules' status and S115 was not OK, maybe this file is not good for this modul:
![kép](https://user-images.githubusercontent.com/98665813/227986806-dac9b1d5-5ab1-4887-aa15-700a665322a1.png)

I had some errors in the terminal:
![kép](https://user-images.githubusercontent.com/98665813/227987021-89632c33-0e1f-4d5f-89d9-4c3aa927703c.png)

The progress bar stuck at the end:
![kép](https://user-images.githubusercontent.com/98665813/227987980-8cfb3b78-d56f-4b2d-9fe7-78fedb622e08.png)

and there was no final state for the scan:
![kép](https://user-images.githubusercontent.com/98665813/227988109-c6453210-9b9b-4bf3-a06c-d4ed7f4c4479.png)

I did the same test in emba only using default-profile + CWE-search and there were no errors, I got the riport at the end.

![kép](https://user-images.githubusercontent.com/98665813/227989096-5256ee16-e0cb-4a24-8e6c-c269fa2187b3.png)

If I select all the categories and the file under test is not suitable for a modul then maybe something goes wrong there, but if I specify a parameter for emba that does not result in a report page then the test still runs fine. In general my problem is that under EMBArk sometimes no result is obtained, even if the partial report is done, but it cannot be accessed from the page, only copied from the filesystem.
I just wanted to collect some problematic files which are easily testable with emba, but some issues can be happen under EMBArk.

This was the end in EMBArk:
![kép](https://user-images.githubusercontent.com/98665813/227994418-e44ec902-6ff7-4845-81e1-f837a35a0e6d.png)

The initial command under EMBArk uses the "-m s120" parameter for CWE-Search, but under emba it is "-c". I have found that under EMBArk, CWE-Search does not start because there is no start or end time in the log for this module.

If you need any retest or info from testing side for the above firmwares, please let me know and I will check the details if something is missing.
