### ISSUE TITLE
emba-input

### ISSUE THREAD

**Issue by BenediktMKuehne** [e-m-b-a/embark#94]
**Describe the bug**
whitelists don't align adequately

**To Reproduce**
try running analysis with device-name containing "-"
5. See error

**Expected behavior**
solution 1: change emba validation
solution 2: change EMBArks validation for inputs

**Screenshots**
![image](https://user-images.githubusercontent.com/62940240/224381235-5411ddec-929d-4d23-ba5a-ab638d259810.png)

![image](https://user-images.githubusercontent.com/62940240/224381772-56f1384a-a01f-4626-bd92-23f062163cad.png)

**Desktop (please complete the following information):**
 - OS: Ubu22

**Comment by BenediktMKuehne** [comment]
![image](https://user-images.githubusercontent.com/62940240/224952907-906d900d-c924-4721-87ec-ec499227123e.png)


input was 1.2.11

**Comment by torabi12** [comment]
I have the same issue:
![image](https://user-images.githubusercontent.com/98665813/224960688-a52ca9d7-29c8-4606-aed9-a2302101bdc5.png)

I think it used to work a few days before.

**Comment by m-1-k-3** [comment]
interesting ... You are not using -X but running into the version check. could you please provide a emba startup command line for reproducing this issue

**Comment by m-1-k-3** [comment]
ignore my comment. Have not seen the version before
