### ISSUE TITLE
Different lengths of labels on X axis

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#95]
**Describe the bug**
The graph uses non-uniform long captions, so the size may be smaller due to wrong titles.

**To Reproduce**
1. Do many scans in EMBArk for different FWs.
2. Check the OS distribution's graph
3. See error

**Expected behavior**
Uniform long labels.

**Screenshots**
![image](https://user-images.githubusercontent.com/98665813/224635249-85c178bb-56e3-4858-80f6-fa7b8d79c2a7.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 22.04.1

**Comment by torabi12** [comment]
Not so nice:
![image](https://user-images.githubusercontent.com/98665813/225099092-0be7878b-4fef-4f5f-b5c9-1aa4adfbf9da.png)

**Comment by m-1-k-3** [comment]
As the correct info is shown we need to think about the way to handle this issue. 
Probably we could just strip the long version details (if the short one is part of the long one) for statistics?

**Comment by torabi12** [comment]
I think the default label like "Linux / vX.YY.ZZZ" would be OK, the 2nd slash and the remaining parts are unnecessary.

**Comment by m-1-k-3** [comment]
Not that easy, as there could be also some other kernel versions e.g. if the firmware update ships multiple kernel versions we can't drop one of them.
On EMBA side I think we need to split the kernel versions and report for every kernel version a separate entry in the f50.csv. On EMBArk side we can then check for the main kernel version and use only this for the dashboard. What do you think @BenediktMKuehne ?

**Comment by BenediktMKuehne** [comment]
> On EMBA side I think we need to split the kernel versions and report for every kernel version a separate entry in the f50.csv

I think that's unnecessary.
The easiest/best would be to just change the rendering filters in EMBArk.

**Comment by BenediktMKuehne** [comment]
@torabi12 would you be able to test the PR for me?

`git remote add testPR https://github.com/BenediktMKuehne/embark`
`git fetch testPR`
`git checkout testPR/95-different-lengths-of-labels-on-x-axis`

and then restart the EMBArk server

**Comment by torabi12** [comment]
Sure, I will, thank you.
Will come back the results end of this day.

**Comment by torabi12** [comment]
I went to ~/embark folder and used your commands and I started the service. The scan was OK, I followed the logs in putty:

![kép](https://user-images.githubusercontent.com/98665813/225709251-b29d5779-b5ac-4577-bee7-e9f7061bbf0a.png)

The detailed view is also OK:
![kép](https://user-images.githubusercontent.com/98665813/225709373-1c9a14fb-0ab4-49fc-81e2-0a1514c5413f.png)

but the main dashboard is emtpy now:

![kép](https://user-images.githubusercontent.com/98665813/225709562-310eeefd-a970-44a3-a089-3652dcee726f.png)

This was a clean system, I installed it a few days ago. I didn't execute the emba_updater before the git commands.
Do you think it is worth to make a brand new installation with testPR/95-different-lengths-of-labels-on-x-axis? I mean
$ git clone https://github.com/BenediktMKuehne/embark.git -b 95-different-lengths-of-labels-on-x-axis
?

**Comment by BenediktMKuehne** [comment]
No, It shouldn't make a difference
I probably made a mistake 😅

**Comment by torabi12** [comment]
If there's a version I can try, please let me know and I'll be happy to test it.

**Comment by BenediktMKuehne** [comment]
@torabi12 
Now it should work

**Comment by torabi12** [comment]
I tested with the same kkeps.bin file, which has a long kernel version but sorry I have the same empty dashboard at the end. Another issue is that the vendor and label creation does not work for me:
![kép](https://user-images.githubusercontent.com/98665813/226710427-36a1e7f8-8f61-4a2b-ac60-20d220a3b08d.png)

the same error for the label creation also.

I followed the scan from terminal and it was OK:

![kép](https://user-images.githubusercontent.com/98665813/226710775-102e12eb-f8cd-4955-aa2c-4575577bae68.png)

The details page looks fine:
![kép](https://user-images.githubusercontent.com/98665813/226711552-a2335c46-10f8-46d1-90db-0000fa770153.png)

**Comment by torabi12** [comment]
I checked again the story on a clean Ubuntu server. I installed
`$ git clone https://github.com/BenediktMKuehne/embark.git -b 95-different-lengths-of-labels-on-x-axis`
but the issues were the same. The scan went fine but the dashboard is empty. I was not able to add vendor and label to the firmware, I got AttributeError like above.

**Comment by BenediktMKuehne** [comment]
@torabi12 now everything should work as expected

**Comment by torabi12** [comment]
It works, but the linux label is long on the dashboard:
![kép](https://user-images.githubusercontent.com/98665813/227532940-8ab01ca1-6eb7-4801-b55d-b045851b851a.png)

and on the details page:
![kép](https://user-images.githubusercontent.com/98665813/227532984-2845055a-018a-40e5-b8d8-7ec1fd04ecc6.png)

Adding vendor and label were OK also.

**Comment by torabi12** [comment]
I may not need to bother with this, but since I've run quite a few tests with partial module selection where S24 was not running, each of these cases has a separate anonymous graph displayed on the dashboard. I think that when running a partial scan you should not create a separate column, which might make the statistics worse, but might give a more accurate result.

![kép](https://user-images.githubusercontent.com/98665813/227723273-601f90db-5151-43e4-bae8-44ee36e0cc9f.png)

**Comment by BenediktMKuehne** [comment]
I'll have to test that particular firmware to find out where that graph comes from.
And adjust the truncation.

**Comment by torabi12** [comment]
I tried today the actual EMBArk, after a scan the dashboard is empty, the entropy frame is missing and detailed view's graphs are also missing.
![image](https://user-images.githubusercontent.com/98665813/229756489-064b39f2-9ae3-4996-a275-adcd6136254d.png)

![image](https://user-images.githubusercontent.com/98665813/229757196-496235bd-e616-4ba6-87f6-9d1ddf4ddb04.png)

and the values are all 0:(

**Comment by torabi12** [comment]
I did a new installation of EMBArk today with a basic scan and the details page is OK:
![kép](https://user-images.githubusercontent.com/98665813/231553460-541a8adc-373b-42cf-b5aa-67e326ce68bf.png)

but the dashboard left empty after the scan:
![kép](https://user-images.githubusercontent.com/98665813/231553546-48d0739d-0a1a-4e68-829e-18949dee0c50.png)

during the scan the terminal dropped these:
![kép](https://user-images.githubusercontent.com/98665813/231554636-97a8b090-a2fb-4b4a-9bad-7039547e113a.png)

Maybe it does not count but I wanted to share with you.

**Comment by torabi12** [comment]
The FW counter and the CPU/MEM graph are working:
![kép](https://user-images.githubusercontent.com/98665813/232537167-bbcefec1-17d9-4110-8281-3b07842fb07e.png)

but the others are empty for me.
