### ISSUE TITLE
s109 page is not reachable

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#97]
**Describe the bug**
I used a custom wordlist file in /embark/emba/config/jtr_wordlist.txt, which contained the good password for the scanned FW.
I executed the same default-profile scan in emba and in EMBArk, and the s109 modul sub page dropped UnicodeDecodeError in the browser, see screenshots.

**To Reproduce**
1. EMBArk installation default mode
2. Start EMBArk: sudo ./run-server.sh -a 192.168.x.x
3. Use the firmware available here: kkeps.bin
4. Open "Cracking identified password hashes" menu
5. See error

**Expected behavior**
Page should be displayed in EMBArk.

**Screenshots**
emba:
![image](https://user-images.githubusercontent.com/98665813/224667357-e6977526-cfcb-4de3-b3be-ee6c470b9971.png)

EMBArk:
![image](https://user-images.githubusercontent.com/98665813/224667408-32fd6acd-3ead-42cb-87ae-957a7f32d9fb.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 22.04.1

**Additional context**
I used this wordlist files with custom modification:
https://github.com/berzerk0/Probable-Wordlists/tree/master/Real-Passwords

Top109Million-probable-v2.txt = jtr_wordlist.txt

**Comment by BenediktMKuehne** [comment]
I'm looking at this...and I don't really know what to do.
If that's the only firmware where this happens, I would just tend to ignore it.
Reason is as follows; Resources should only be accessed through EMBArk and since this requires the html-template-render functionality.

This could be a bug inside the Django framework though.
Could you extract that html page from the log-files and post it here?

**Comment by torabi12** [comment]
Hello,

I am sending the html-report folder from EMBArk.
[html-report.zip](https://github.com/e-m-b-a/embark/files/10957517/html-report.zip)

In this version the s109 page is opened. The problem only opening the EMBArk page / report / Open Report / Cracking identified password hashes.

I have checked all the sub pages and this is the only one which is not OK.

**Comment by torabi12** [comment]
Iam going to try the same with another binary file. I used kkeps.bin for an old SmartPlug device. I thought that is good for testing because I knew the password inside and I wanted to get back the result from EMBA in the report.

**Comment by torabi12** [comment]
I have good news. I reexecuted the same test in EMBArk today (upgraded today also) and the s109 page was displayed correctly.
![image](https://user-images.githubusercontent.com/98665813/225097939-76a73107-165e-42f3-8cb1-3ae6006ad3e3.png)

The bad news is that emba was not able to crack the hash, but the jtr_wordlist.txt file contained the solution in the last line and it was working a few days before:

![image](https://user-images.githubusercontent.com/98665813/225098427-840d2f1e-34e9-4712-b87a-fc7e3bdfe413.png)

I suggest to close this bug, and I would like to open a new one later for the JTR issue if you agree.
