### ISSUE TITLE
Delete button on report page

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#98]
**Is your feature request related to a problem? Please describe.**
EMBArk's report page displays all the successful and failed scans. If I reexecute a test it will provide new line on the page. I think the user should be able to delete manually the unnecessary lines even if it was good or failed. The rescan/delete button just allows the user to delete the uploaded FW file which is perfect. Deleting the uploaded FW should leave the test result on the report page like works correctly.

**Describe the solution you'd like**
A new delete option for the scan result may allow the user to maintain the report page on long term.

**Additional context**
![image](https://user-images.githubusercontent.com/98665813/225261308-32a92e27-aac9-4c5d-b23b-51f66bd6789c.png)

**Comment by m-1-k-3** [comment]
We put this on our future todo list.
Pull requests are welcome.
