### ISSUE TITLE
Smaller graph on Device Tracker page

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#99]
**Is your feature request related to a problem? Please describe.**
The Device Tracker shows a graph of the selected item but the size is too large in my opinion. Maybe half of the size would be enough and the background picture quality is low on this page. I know it’s a minor issue, and maybe it is only my opinion, but I think the readability would be better in smaller size.

**Describe the solution you'd like**
I think on an average screen resolution 1920x1200 the graph should be fit on the page with all categories on the top, below and sides to see the whole status of the actual FW charactersitics.

**Comment by BenediktMKuehne** [comment]
tracker will move towards tracking sbom results
issue iw now outdated
